### PR TITLE
Fix `across()` and `cur_data()` to work sequentially

### LINKED ISSUE #4907: `across()` doesn't work sequentially
`xx` should return `2` below. I think the problem is that `across()` is using the `mask$full_data()` to look up the data to `eval_select()` with, but this is a static copy of the original data set, and is not updated between expressions. I think it needs to use the `mask$bindings` somehow?

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(a = 1)

df %>%
  mutate(
    x = ncol(across(is.numeric)), 
    xx = ncol(across(is.numeric))
  )
#>   a x xx
#> 1 1 1  1
```

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #4907 

This PR fixes both `across()` and `cur_data()` when used in sequential expressions.

This was actually incredibly hard to get right. This is complicated by the fact that we don't want to resolve "unused" columns, which would mark them as "used", but we still have to check their types in `eval_select()` if something like `across(is.numeric)` is called.

The idea here is to separate the non-group columns that are currently present in the data into two groups. The first group are unused columns, which we pull from the original data. The second are used columns, which we pull from the current bindings.

The good news is that, even though this is more expensive, it is part of the "set up" work that gets cached in #4909. I'll rework that PR on top of this

### CODE REVIEW

**Comment by DavisVaughan** [comment]
I also discovered to my horror that if you `c()` two length-0 named lists together, you get an unnamed list back. This broke `eval_select()` (as it should), but luckily `vec_c()` works correctly.

``` r
library(vctrs)
library(tidyselect)
library(rlang)

x <- list(x = 1)
x <- x[0]
x
#> named list()

# WHY?
c(x, x)
#> list()

vec_c(x, x)
#> named list()

eval_select(expr(everything()), c(x, x))
#> Error: Can't select within an unnamed vector.

eval_select(expr(everything()), vec_c(x, x))
#> named integer(0)
```

<sup>Created on 2020-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

File: R/across.R [hunk 1]
```diff
@@ -62,15 +62,49 @@
...
-  )
-  data <- mask$pick(names(vars))
+  original_data <- mask$full_data()
+  group_vars <- group_vars(original_data)
+  original_data <- unclass(original_data)
+  original_vars <- names(original_data)
+
+  current_vars <- mask$current_vars()
+
+  # Allowed columns are any non-group columns in the current data
```
Comment (hadley) [inline R/across.R]: I wonder if more of this logic should move inside of the mask, since it's now working with a bunch of internal details.

Comment (romainfrancois) [reply R/across.R]: Maybe in `$pick()` or in a `$across()`
