### PR TITLE
... are further delayed in top_across()

### LINKED ISSUE #5813: `...` of `across()` are evaluated too early?
Not sure why this doesn't work:

```r
library(dplyr)

tibble(x = tibble(foo = 1)) %>%
  mutate(across(
    everything(),
    mutate,
    foo = foo + 1
  ))
#> Error: Problem with `mutate()` input `..1`.
#> ✖ object 'foo' not found
#> ℹ Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
```

Ideally `across()` would work the same way as `map()`:

```r
tibble(x = tibble(foo = 1)) %>%
  map(
    mutate,
    foo = foo + 1
  )
#> $x
#> # A tibble: 1 x 1
#>     foo
#>   <dbl>
#> 1     2
```

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5813

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = tibble(foo = 1)) %>%
  mutate(across(
    everything(),
    mutate, 
    foo = foo + 1
  ))
#> # A tibble: 1 x 1
#>   x$foo
#>   <dbl>
#> 1     2
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

File: R/across.R [hunk 1]
```diff
@@ -370,7 +370,7 @@ top_across <- function(.cols = everything(), .fns = NULL, ..., .names = NULL) {
 
   expressions <- vector(mode = "list", n_vars * n_fns)
   columns <- character(n_vars * n_fns)
-  extra_args <- list(...)
+  extra_args <- enquos(...)
```
Comment (lionel-) [inline R/across.R:373]: As mentioned in https://github.com/tidyverse/dplyr/issues/5813#issuecomment-796619712 this will cause double evaluation of the expressions in `...`. We need promise semantics.

I don't fully understand how evaluation is set up here but it looks like you're evaluating calls locally? In this case you could just use `quote(...)` below

```r
call <- call2(fn, sym(var), quote(...))
```

Comment (lionel-) [reply R/across.R:373]: Also need to add tests with something like `rnorm()` to check that all columns get a unique random value and not different ones.

Comment (lionel-) [reply R/across.R:373]: If evaluation is not local, then you could create a child of the environment in which to evaluate and bind `...` to the local dots. These can be captured with:

```r
env_dots <- function(...) get("...")
```

Comment (romainfrancois) [reply R/across.R:373]: `top_across()` only create the calls, to be evaluated later in either `summarise()` or `mutate()`, so that if you have: 

`across(c(x, y), mean, ...)` you get two calls: 

 - `x = mean(x, <...>)`
 - `y = mean(y, <...>)`

Comment (romainfrancois) [reply R/across.R:373]: `list(...)` that we had before was evaluating inside `top_across()` before the calls are made, but then that is #5813 

I'll have a look at the `env_dots` way because indeed it's not local, so would get the "used in an incorrect context" thing

**Comment by lionel-** [comment]
Ready for another round of review @romainfrancois

File: R/mutate.R [hunk 2]
```diff
@@ -256,7 +256,7 @@ mutate_cols <- function(.data, ..., caller_env) {
 
       # get results from all the quosures that are expanded from ..i
       # then ingest them after
-      quosures <- expand_quosure(dots[[i]])
+      quosures <- expand_across(dots[[i]])
```
Comment (romainfrancois) [inline R/mutate.R:259]: At some point we might want to do more than "expand across" here, e.g. perhaps we can expand `if_any/all()` also, and generally have some sort of mechanism for setup work, so we might add another layer, but for the moment this is more readable.

**Review by romainfrancois — COMMENTED** [review]
Thanks @lionel-. This looks great. 

Eventually we might have more than `expand_across()`, i.e. other things to do with `summarise(...=)` but in the meantime, this looks great.

File: R/mutate.R (hunk 2 above)
Comment (lionel-) [reply R/mutate.R:259]: yup that makes sense.
