### PR TITLE
summarise() silently ignore NULL results.

### LINKED ISSUE #5708: Silently drop NULLs in summarise()?
This would be consistent with our general principles for handling `NULL`, and would support workflows like this:

``` r
library(dplyr, warn.conflicts = FALSE)
cond <- FALSE
mtcars %>% 
  summarise(
    always = mean(gear),
    optional = if(cond) mean(hp)
  )
#> Error: Problem with `summarise()` input `optional`.
#> x Input `optional` must be a vector, not NULL.
#> ℹ Input `optional` is `if (cond) mean(hp)`.
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

From https://twitter.com/pheymanss/status/1354116324159606785

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5708

silently ignoring when *all the results* are NULL, and otherwise shout: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(x = 1:2, g = 1:2) %>% group_by(g)

# silently ignored
summarise(df, x = NULL)
#> # A tibble: 2 x 1
#>       g
#> * <int>
#> 1     1
#> 2     2

# mix of NULL and non NULL -> error
summarise(df, x = if(g == 1) 42)
#> Error: Problem with `summarise()` input `x`.
#> x `x` must return compatible vectors across groups.
#> ℹ Cannot combine NULL and non NULL results.
#> ℹ Input `x` is `if (g == 1) 42`.
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by romainfrancois** [comment]
I can squeeze that in for 1.0.4 or wait.

File: R/summarise.R [hunk 1]
```diff
@@ -227,7 +227,13 @@ summarise_cols <- function(.data, ...) {
       # evaluating the quosure in the "sliced data mask"
       #
       # TODO: reinject hybrid evaluation at the R level
-      chunks[[i]] <- mask$eval_all_summarise(quo)
+      results <- mask$eval_all_summarise(quo)
+
+      if (is.null(results)) {
```
Comment (hadley) [inline R/summarise.R:232]: It took me a minute to realise why this was necessary — otherwise I guess `chunks[[i]]` gets removed.

File: tests/testthat/test-summarise-errors.txt [hunk 2]
```diff
@@ -28,15 +28,13 @@ i Input `a` is `rlang::env(a = 1)`.
 Error: Problem with `summarise()` input `a`.
 x Input `a` must be a vector, not an environment.
 i Input `a` is `rlang::env(a = 1)`.
```
Comment (hadley) [inline tests/testthat/test-summarise-errors.txt:30]: Why did this change?

File: tests/testthat/test-summarise.r [hunk 3]
```diff
@@ -210,6 +210,13 @@ test_that("summarise() casts data frame results to common type (#5646)", {
   expect_equal(res$z, c(NA, 2))
 })
 
+test_that("summarise() silently skips when all results are NULL (#5708)", {
+  df <- data.frame(x = 1:2, g = 1:2) %>% group_by(g)
+
+  expect_equal(summarise(df, x = NULL), summarise(df))
+  expect_error(summarise(df, x = if(g == 1) 42))
```
Comment (hadley) [inline tests/testthat/test-summarise.r:217]: If we used testthat 3e, we could use `expect_snapshot(..., error = TRUE)`. We should probably upgrade at some point (not for this PR).

File: R/summarise.R (hunk 1 above)
Comment (romainfrancois) [reply R/summarise.R:232]: yeah, the `some_list[[i]] <- NULL` thing gets me even single time

File: tests/testthat/test-summarise.r (hunk 3 above)
Comment (romainfrancois) [reply tests/testthat/test-summarise.r:217]: https://github.com/tidyverse/dplyr/issues/5712

File: tests/testthat/test-summarise-errors.txt (hunk 2 above)
Comment (romainfrancois) [reply tests/testthat/test-summarise-errors.txt]: Thanks. Fixed now.
