### PR TITLE
Coerce join inputs into tibbles

### LINKED ISSUE #4917: join_mutate(x = <sf>)
``` r
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
library(qualmap)
library(dplyr, warn.conflicts = FALSE)

sf <- mutate(stLouis, TRACTCE = as.numeric(TRACTCE))
df <- tibble(TRACTCE = 112100, x = 1)

left_join(sf, df)
#> Joining, by = "TRACTCE"
#> Error: `nm` must be `NULL` or a character vector the same length as `x`
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

This happens here: https://github.com/tidyverse/dplyr/blob/master/R/join.r#L296

```r
x_key <- set_names(x[vars$x$key], names(vars$x$key))
```

because `x` is an `sf` object and the `[` method brings back the `geometry` column, so `x[vars$x$key]` does not have the same number of columns as the length of `names(vars$x$key)`

### PR DESCRIPTION
**Pull request by hadley**
This ensures that we always know what methods are being called, and predicts us against variations in subclass implementations. The main downside of this approach is that we can no longer translate grouping variable names in the presence of ambiguity

Fixes #4917

### CODE REVIEW

File: R/join.r [hunk 1]
```diff
@@ -324,12 +324,15 @@ join_mutate <- function(x, y, by, type,
   vars <- join_cols(tbl_vars(x), tbl_vars(y), by = by, suffix = suffix, keep = keep)
   na_equal <- check_na_matches(na_matches)
 
-  x_key <- set_names(x[vars$x$key], names(vars$x$key))
-  y_key <- set_names(y[vars$y$key], names(vars$y$key))
+  x_in <- as_tibble(x)
+  y_in <- as_tibble(y)
```
Comment (krlmlr) [inline R/join.r]:
```suggestion
  x_in <- as_tibble(x, .name_repair = "minimal")
  y_in <- as_tibble(y, .name_repair = "minimal")
```
