### PR TITLE
slice handles 0 in positive and negative indices. closes #3313

### LINKED ISSUE #3313: Using `slice()` with a row number vector which includes 0 results in wrong output
If one uses `slice()` with a row number vector which includes 0 *and* other row numbers, wrong output is produced. Here’s a repexp:

``` r
library(dplyr)

# Example data
d = tibble(x = 1:5, y = LETTERS[1:5])

# This command works fine (returns a zero-row subset)
slice(d, 0)
#> # A tibble: 0 x 2
#> # ... with 2 variables: x <int>, y <chr>

# But these commands give incorrect output
slice(d, c(0, 1))
#> # A tibble: 1 x 2
#>       x y    
#>   <int> <chr>
#> 1    NA <NA>
slice(d, c(0, 1, 2))
#> # A tibble: 2 x 2
#>       x y    
#>   <int> <chr>
#> 1    NA <NA> 
#> 2     1 A
slice(d, c(-1, 0))
#> # A tibble: 3 x 2
#>       x y    
#>   <int> <chr>
#> 1     3 C    
#> 2     4 D    
#> 3     5 E
slice(d, c(0, -1))
#> # A tibble: 3 x 2
#>       x y    
#>   <int> <chr>
#> 1     3 C    
#> 2     4 D    
#> 3     5 E

# Subsetting using base R functions works fine, i.e. gives the expected output
d[0, ]
#> # A tibble: 0 x 2
#> # ... with 2 variables: x <int>, y <chr>
d[c(0, 1), ]
#> # A tibble: 1 x 2
#>       x y    
#>   <int> <chr>
#> 1     1 A
d[c(0, 1, 2), ]
#> # A tibble: 2 x 2
#>       x y    
#>   <int> <chr>
#> 1     1 A    
#> 2     2 B
d[c(-1, 0), ]
#> # A tibble: 4 x 2
#>       x y    
#>   <int> <chr>
#> 1     2 B    
#> 2     3 C    
#> 3     4 D    
#> 4     5 E
d[c(0, -1), ]
#> # A tibble: 4 x 2
#>       x y    
#>   <int> <chr>
#> 1     2 B    
#> 2     3 C    
#> 3     4 D    
#> 4     5 E
```

### PR DESCRIPTION
**Pull request by romainfrancois**
- slice handles 0 in positive and negative indices (#3313)

--- 

See #3313 for details, this fixes it but I wonder if instead of skipping the 0 we should make them illegal here, as `slice` should expect either strictly positive (to keep) or strictly negative (to drop). 

```
slice( d, c(0,1) )
```

But there seems to be some tolerance for it in R: 

```
> x <- 1:10
> x[0]
integer(0)
> x[c(0,1)]
[1] 1
```

### CODE REVIEW

**Comment by romainfrancois** [comment]
@krlmlr let me know if the message in the PR is what you expect for the generation of NEWS

File: src/slice.cpp [hunk 1]
```diff
@@ -83,7 +83,7 @@ DataFrame slice_grouped(GroupedDataFrame gdf, const QuosureList& dots) {
       // positive indexing
       int ntest = g_test.size();
       for (int j = 0; j < ntest; j++) {
-        if (!(g_test[j] > nr || g_test[j] == NA_INTEGER)) {
+        if (!(g_test[j] > nr || g_test[j] < 1)) {
```
Comment (krlmlr) [inline src/slice.cpp]: We currently fail if positive and negative indexes are used, but this change seems to silently ignore negatives (including `NA`):

``` r
dplyr::slice(iris, c(1, -1))
#> Error in slice_impl(.data, dots): Indices must be either all positive or all negative, not a mix of both. Found 1 positive indices and 1 negative indices
```

> Created on 2018-03-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Also, I'm struggling with `!(... || ...)` , can you please refactor?

Comment (krlmlr) [reply src/slice.cpp]: Do we have a test for `slice(c(-1, 1))` ?

Comment (krlmlr) [reply src/slice.cpp]: We do, but perhaps not for `slice(c(1, -1))` ?

**Comment by krlmlr** [comment]
Oh, I see you added the "closes #xxxx" to the title. Missed that.

File: src/slice.cpp (hunk 1 above)
Comment (romainfrancois) [reply src/slice.cpp]: When we are in the `positive indexing` branch we already know that we either have only positive

Comment (krlmlr) [reply src/slice.cpp]: I see. Can you please add comments to the fact that we're ignoring both 0 and NA here (because NA happens to be -2³¹)?

I'll work on reducing code duplication in #2311.

**Comment by krlmlr** [comment]
Thanks!

**Comment by krlmlr** [comment]
Looks we need to write "closes #xxx" in the body after all...
