### PR TITLE
`group_by_at` can group by an existing grouping variable. closes #3351

### LINKED ISSUE #3351: group_by_at() doesn't handle existig grouping correctly
`group_by_at(tbl)` is confused if `tbl` is already a grouped tibble and new grouping uses some of variables that were used in this previously existing grouping. Instead of overwriting this existing grouping (as `group_by()` does by default) it returns tibble grouped only by variables that wern't used in previosuly defined grouping (and throws a warning about nonexistence of variables common for existing and newly defined grouping).

```r
library(dplyr)
#> 
#> Dołączanie pakietu: 'dplyr'
#> Następujące obiekty zostały zakryte z 'package:stats':
#> 
#>     filter, lag
#> Następujące obiekty zostały zakryte z 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# some grouped tibble
tbl = tibble(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
  group_by(gr1)

# doesn't work
tbl %>%
  group_by_at(vars(one_of("gr1", "gr2"))) %>%
  summarise(xSum = sum(x))
#> Warning: Unknown variables: `gr1`

#> Warning: Unknown variables: `gr1`
#> # A tibble: 2 x 2
#>     gr2  xSum
#>   <int> <int>
#> 1     1    10
#> 2     2    26

# adding ungroup() before group_by_at() helps
tbl %>%
  ungroup() %>%
  group_by_at(vars(one_of("gr1", "gr2"))) %>%
  summarise(xSum = sum(x))
#> # A tibble: 4 x 3
#> # Groups:   gr1 [?]
#>     gr1   gr2  xSum
#>   <int> <int> <int>
#> 1     1     1     4
#> 2     1     2    12
#> 3     2     1     6
#> 4     2     2    14

# however group_by() works without such workaround
tbl %>%
  group_by(gr1, gr2) %>%
  summarise(xSum = sum(x))
#> # A tibble: 4 x 3
#> # Groups:   gr1 [?]
#>     gr1   gr2  xSum
#>   <int> <int> <int>
#> 1     1     1     4
#> 2     1     2    12
#> 3     2     1     6
#> 4     2     2    14
```

### PR DESCRIPTION
**Pull request by romainfrancois**
This passes the test, but I'm a bit uneasy with the change in `tbl_at_vars` 

This was probably using `tbl_nongroup_vars` for a reason, but whatever that was, it's not captured by tests.

### CODE REVIEW

File: R/colwise.R [hunk 1]
```diff
@@ -120,7 +120,7 @@ print.any_vars <- function(x, ...) {
 
 # Requires tbl_vars() method
 tbl_at_vars <- function(tbl, vars) {
-  tibble_vars <- tbl_nongroup_vars(tbl)
+  tibble_vars <- tbl_vars(tbl)
```
Comment (romainfrancois) [inline R/colwise.R]: @lionel- Will this break something else. I guess we probably don't want to be able to get grouping variables in `mutate_at`, but `filter_at` and `group_by_at` should be fine. 

I'll try to stress other users of `tbl_at_vars`

Comment (krlmlr) [reply R/colwise.R]: Maybe we can return the information if a var is grouped or not? Return a data frame with two columns `var` and `grouped` (logical)?

Comment (lionel-) [reply R/colwise.R]: I'll discuss this with Hadley, we have a meeting later today.

**Comment by romainfrancois** [comment]
😱 I've broken `select_at` 

```r
> tbl = tibble(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
+   group_by(gr1)
> 
> select_at( tbl, vars(gr2) )
# A tibble: 8 x 2
# Groups:   gr1 [2]
    gr1   gr2
  <int> <int>
1     1     1
2     2     1
3     1     1
4     2     1
5     1     2
6     2     2
7     1     2
8     2     2
> select_at( tbl, vars(gr1) )
 Show Traceback
 
 Rerun with Debug
 Error: `nm` must be `NULL` or a character vector the same length as `x` 
```

**Comment by romainfrancois** [comment]
I'm happy with this one. but it might deserve some attention from @lionel- / @krlmlr as I've messed with `vars_select_syms` to make it work.

**Comment by lionel-** [comment]
So the principle is that colwise verbs should have the same restrictions as their singular counterpart. The `_at()` verbs should be able to act on grouping variables and the `_all()` verbs should include those as well.

**Comment by romainfrancois** [comment]
that seems to be the case here. Maybe it needs more testing for each of the verbs.

**Comment by lionel-** [comment]
> Maybe it needs more testing for each of the verbs.

That'd be great. Could you also take a look at the `_all` variants please? For instance `rename_all()` should also rename the grouping variables.

**Comment by krlmlr** [comment]
@romainfrancois: #3431 should make this a bit easier, but will lead to more conflicts in this PR. Would you like me to take over?

File: tests/testthat/test-colwise-mutate.R [hunk 2]
```diff
@@ -110,6 +110,16 @@ test_that("can use a purrr-style lambda", {
   expect_identical(summarise_at(mtcars, vars(1:2), ~mean(.x)), summarise(mtcars, mpg = mean(mpg), cyl = mean(cyl)))
 })
 
+test_that("mutate_at refuses to mutate a grouping variable (#3351)", {
+  tbl <- data_frame(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
+      group_by(gr1)
+
+  expect_error(
+    mutate_at(tbl, vars(gr1), sqrt),
+    "Column `gr1` can't be modified because it's a grouping variable"
```
[the remark this answers is not in the document]
Comment (romainfrancois) [reply tests/testthat/test-colwise-mutate.R]: ✔️

File: tests/testthat/test-colwise-select.R [hunk 3]
```diff
@@ -56,6 +56,16 @@ test_that("can select/rename with vars()", {
   expect_identical(rename_at(df, vars(x:y), toupper), set_names(df, c("X", "Y", "z")))
 })
 
+test_that("select_at can use grouping variables", {
```
[the remark this answers is not in the document]
Comment (romainfrancois) [reply tests/testthat/test-colwise-select.R]: ✔️

**Comment by romainfrancois** [comment]
@krlmlr yes this looks very relevant. I see that you merged #3431, so I'll rebase this branch on master, deal with the conflicts and carry on this issue's issues.

**Comment by romainfrancois** [comment]
Do we expect this: 

```
> tbl <- data_frame(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
+     group_by(gr1)
> tbl
# A tibble: 8 x 3
# Groups:   gr1 [2]
    gr1   gr2     x
  <int> <int> <int>
1     1     1     1
2     2     1     2
3     1     1     3
4     2     1     4
5     1     2     5
6     2     2     6
7     1     2     7
8     2     2     8
> arrange_if(tbl, is.integer)
# A tibble: 8 x 3
# Groups:   gr1 [2]
    gr1   gr2     x
  <int> <int> <int>
1     1     1     1
2     2     1     2
3     1     1     3
4     2     1     4
5     1     2     5
6     2     2     6
7     1     2     7
8     2     2     8
```

i.e. that `arrange_if` not considering the grouping variables ?

**Comment by krlmlr** [comment]
How does `arrange()` behave, especially w.r.t. the grouping index?

**Comment by romainfrancois** [comment]
It deals with it: 

```r
> arrange(tbl, gr1, gr2, x)
# A tibble: 8 x 3
# Groups:   gr1 [2]
    gr1   gr2     x
  <int> <int> <int>
1     1     1     1
2     1     1     3
3     1     2     5
4     1     2     7
5     2     1     2
6     2     1     4
7     2     2     6
8     2     2     8
> arrange_all(tbl)
# A tibble: 8 x 3
# Groups:   gr1 [2]
    gr1   gr2     x
  <int> <int> <int>
1     1     1     1
2     1     1     3
3     1     2     5
4     1     2     7
5     2     1     2
6     2     1     4
7     2     2     6
8     2     2     8
```

**Comment by romainfrancois** [comment]
and the metadata is correct after it: 

```
> attributes( arrange_all(tbl)  )
$row.names
[1] 1 2 3 4 5 6 7 8

$class
[1] "grouped_df" "tbl_df"     "tbl"        "data.frame"

$vars
[1] "gr1"

$drop
[1] TRUE

$indices
$indices[[1]]
[1] 0 1 2 3

$indices[[2]]
[1] 4 5 6 7


$group_sizes
[1] 4 4

$biggest_group_size
[1] 4

$names
[1] "gr1" "gr2" "x"  

$labels
  gr1
1   1
2   2
```

**Comment by krlmlr** [comment]
Then I think `arrange_if()` et al. should extend to grouping variables.

**Comment by romainfrancois** [comment]
I've added many tests. Please have a look that this reprex captures what is supposed to happen. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tbl <- data_frame(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
  group_by(gr1)

# arrange
arrange_all(tbl)
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     1     1     3
#> 3     1     2     5
#> 4     1     2     7
#> 5     2     1     2
#> 6     2     1     4
#> 7     2     2     6
#> 8     2     2     8
arrange_if(tbl, is.integer)
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     1     1     3
#> 3     1     2     5
#> 4     1     2     7
#> 5     2     1     2
#> 6     2     1     4
#> 7     2     2     6
#> 8     2     2     8
arrange_at(tbl, vars(gr1))
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     1     1     3
#> 3     1     2     5
#> 4     1     2     7
#> 5     2     1     2
#> 6     2     1     4
#> 7     2     2     6
#> 8     2     2     8

# filter
filter_at( tbl, vars(gr1), all_vars(.>1))
#> # A tibble: 4 x 3
#> # Groups:   gr1 [1]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     2     1     2
#> 2     2     1     4
#> 3     2     2     6
#> 4     2     2     8
filter_all( tbl, all_vars(.>1))
#> # A tibble: 2 x 3
#> # Groups:   gr1 [1]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     2     2     6
#> 2     2     2     8
filter_if( tbl, is.integer, all_vars(.>1))
#> # A tibble: 2 x 3
#> # Groups:   gr1 [1]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     2     2     6
#> 2     2     2     8

# group_by
group_by_at(tbl, vars(gr1, gr2))
#> # A tibble: 8 x 3
#> # Groups:   gr1, gr2 [4]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8
group_by_all(tbl)
#> # A tibble: 8 x 3
#> # Groups:   gr1, gr2, x [8]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8
group_by_if(tbl, is.integer)
#> # A tibble: 8 x 3
#> # Groups:   gr1, gr2, x [8]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8

# mutate
mutate_at(tbl, vars(gr1), sqrt)  # expected error
#> Error in mutate_impl(.data, dots): Column `gr1` can't be modified because it's a grouping variable
mutate_all(tbl, sqrt)            # only ungrouped treated
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <dbl> <dbl>
#> 1     1  1.00  1.00
#> 2     2  1.00  1.41
#> 3     1  1.00  1.73
#> 4     2  1.00  2.00
#> 5     1  1.41  2.24
#> 6     2  1.41  2.45
#> 7     1  1.41  2.65
#> 8     2  1.41  2.83
mutate_if(tbl, is.integer, sqrt) # only ungrouped treated
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <dbl> <dbl>
#> 1     1  1.00  1.00
#> 2     2  1.00  1.41
#> 3     1  1.00  1.73
#> 4     2  1.00  2.00
#> 5     1  1.41  2.24
#> 6     2  1.41  2.45
#> 7     1  1.41  2.65
#> 8     2  1.41  2.83

# transmute
transmute_at(tbl, vars(gr1), sqrt)  # expected error
#> Error in mutate_impl(.data, dots): Column `gr1` can't be modified because it's a grouping variable
transmute_all(tbl, sqrt)            # only ungrouped treated
#> Adding missing grouping variables: `gr1`
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <dbl> <dbl>
#> 1     1  1.00  1.00
#> 2     2  1.00  1.41
#> 3     1  1.00  1.73
#> 4     2  1.00  2.00
#> 5     1  1.41  2.24
#> 6     2  1.41  2.45
#> 7     1  1.41  2.65
#> 8     2  1.41  2.83
transmute_if(tbl, is.integer, sqrt) # only ungrouped treated
#> Adding missing grouping variables: `gr1`
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <dbl> <dbl>
#> 1     1  1.00  1.00
#> 2     2  1.00  1.41
#> 3     1  1.00  1.73
#> 4     2  1.00  2.00
#> 5     1  1.41  2.24
#> 6     2  1.41  2.45
#> 7     1  1.41  2.65
#> 8     2  1.41  2.83

# rename
rename_at(tbl, vars(gr1), toupper)
#> # A tibble: 8 x 3
#> # Groups:   GR1 [2]
#>     GR1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8
rename_all(tbl, toupper)
#> # A tibble: 8 x 3
#> # Groups:   GR1 [2]
#>     GR1   GR2     X
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8
rename_if(tbl, is.integer, toupper)
#> # A tibble: 8 x 3
#> # Groups:   GR1 [2]
#>     GR1   GR2     X
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8

# select
select_at(tbl, vars(gr1))
#> # A tibble: 8 x 1
#> # Groups:   gr1 [2]
#>     gr1
#>   <int>
#> 1     1
#> 2     2
#> 3     1
#> 4     2
#> 5     1
#> 6     2
#> 7     1
#> 8     2
select_all(tbl)
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8
select_if(tbl, is.integer)
#> # A tibble: 8 x 3
#> # Groups:   gr1 [2]
#>     gr1   gr2     x
#>   <int> <int> <int>
#> 1     1     1     1
#> 2     2     1     2
#> 3     1     1     3
#> 4     2     1     4
#> 5     1     2     5
#> 6     2     2     6
#> 7     1     2     7
#> 8     2     2     8

# summarise
summarise_at(tbl, vars(gr1), mean)  # expected error
#> Error in summarise_impl(.data, dots): Column `gr1` can't be modified because it's a grouping variable
summarise_all(tbl, mean)            # only ungrouped treated
#> # A tibble: 2 x 3
#>     gr1   gr2     x
#>   <int> <dbl> <dbl>
#> 1     1  1.50    4.
#> 2     2  1.50    5.
summarise_if(tbl, is.integer, mean) # only ungrouped treated
#> # A tibble: 2 x 3
#>     gr1   gr2     x
#>   <int> <dbl> <dbl>
#> 1     1  1.50    4.
#> 2     2  1.50    5.
```

Created on 2018-03-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

File: R/colwise-group-by.R [hunk 4]
```diff
@@ -31,18 +31,18 @@ group_by_all <- function(.tbl, .funs = list(), ...) {
 #' @rdname group_by_all
 #' @export
 group_by_at <- function(.tbl, .vars, .funs = list(), ..., .add = FALSE) {
-  funs <- manip_at(.tbl, .vars, .funs, enquo(.funs), caller_env(), ...)
+  funs <- manip_at(.tbl, .vars, .funs, enquo(.funs), caller_env(), .include_group_vars = TRUE, ...)
```
Comment (krlmlr) [inline R/colwise-group-by.R]: `group_by_all()` ?

File: R/colwise-arrange.R [hunk 5]
```diff
@@ -26,18 +26,18 @@ arrange_all <- function(.tbl, .funs = list(), ...) {
 #' @rdname arrange_all
 #' @export
 arrange_at <- function(.tbl, .vars, .funs = list(), ...) {
-  funs <- manip_at(.tbl, .vars, .funs, enquo(.funs), caller_env(), ...)
+  funs <- manip_at(.tbl, .vars, .funs, enquo(.funs), caller_env(), .include_group_vars = TRUE, ...)
```
[the remark this answers is not in the document]
Comment (romainfrancois) [reply R/colwise-arrange.R]: 😱

**Comment by romainfrancois** [comment]
@krlmlr it is the same message as in 

```r
> transmute(tbl, gr2 = sqrt(gr2), x = sqrt(x))
Adding missing grouping variables: `gr1`
# A tibble: 8 x 3
# Groups:   gr1 [2]
    gr1   gr2     x
  <int> <dbl> <dbl>
1     1  1.00  1.00
2     2  1.00  1.41
3     1  1.00  1.73
4     2  1.00  2.00
5     1  1.41  2.24
6     2  1.41  2.45
7     1  1.41  2.65
8     2  1.41  2.83
```

File: R/colwise-group-by.R (hunk 4 above)
Comment (romainfrancois) [reply R/colwise-group-by.R]: what do you mean ?

**Comment by romainfrancois** [comment]
Alright, I'll fix that.

File: R/colwise-group-by.R (hunk 4 above)
Comment (krlmlr) [reply R/colwise-group-by.R]: Do we need to update `group_by_all()`? Also, what should the order of group variables be, for an already grouped data frame? Do we have tests for both `.add = FALSE` and `.add = TRUE` ?

Comment (romainfrancois) [reply R/colwise-group-by.R]: Rigth, so that's two things
- test for .add = TRUE and .add = FALSE in `group_by_at`
- test `group_by_all`

as far as I understand it, `group_by_all` should just group by all the variables in the order of the data, no matter if it's already grouped or not.

Comment (krlmlr) [reply R/colwise-group-by.R]: Yes.

I'm not sure about the order of grouping variables. `.add = TRUE` perhaps should just append the variables and use the original ordering, `.add = FALSE` should use the ordering from the data. Unfortunately, dplyr 0.7.4 and earlier always uses the ordering from the data, that's what we should be doing here even if it's inconsistent.

**Comment by romainfrancois** [comment]
I just remove the message entirely. `mutate_all` and `mutate_if` don't have the message, and it feels natural not to have a message there. 

To call `ensure_group_vars` with `notify=FALSE`, I had to copy the code from `select.grouped_df` in `transmute.grouped_df`. The alternative would have been to add a `.notify` argument to `select.grouped_df`

**Comment by krlmlr** [comment]
It feels that `transmute()` needs the message because it's also a selection operator. Can you extract a function from `select.grouped_df()` that has the `.notify` argument, so that we don't need to change the API?

**Comment by krlmlr** [comment]
Thanks! Please ping me when you're ready for another round.

**Comment by krlmlr** [comment]
Can you please also double-check the following code:

```r
tibble(a = 1, b = 2) %>% group_by(a) %>% select(notify = b)
```

**Comment by romainfrancois** [comment]
I get this: 

```r
> tibble(a = 1, b = 2) %>% group_by(a) %>% select(notify = b)
Adding missing grouping variables: `a`
# A tibble: 1 x 2
# Groups:   a [1]
      a notify
  <dbl>  <dbl>
1    1.     2.
```

that seems ok. Where does this come from ? Should this be a unit test ?

**Comment by krlmlr** [comment]
No, that's fine. Now I understand how and why `!!!quos(...)` works ;-)

File: R/manip.r [hunk 6]
```diff
@@ -315,6 +315,21 @@ transmute_.default <- function(.data, ..., .dots = list()) {
   transmute(.data, !!!dots)
 }
 
+#' @export
+transmute.grouped_df <- function(.data, ...) {
+  dots <- named_quos(...)
+  out <- mutate(.data, !!!dots)
+  keep <- names(dots)
+
+  .select_grouped_df(out, one_of(keep), notify=FALSE)
```
Comment (krlmlr) [inline R/manip.r]: `transmute()` is an implicit selection operator, I still think we should notify if it keeps variables we didn't intend to keep.

To avoid the irritating from `transmute_all()`, can we just forward `transmute_all()` to `mutate_all()`, which is currently silent?

Later, we should explicitly add the grouping variables in the `transmute()` call issued by `transmute_all()` and show a different message, like ``"Not changing grouping variables `gr1`, `gr2`"`` (#3473).

File: tests/testthat/test-colwise-group-by.R [hunk 7]
```diff
@@ -14,3 +14,24 @@ test_that("group_by_ verbs accept optional operations", {
...
+    group_by(tbl, gr1, gr2)
+  )
+
+  expect_identical(
+    group_by_all(tbl),
+    group_by(tbl, gr1, gr2, x)
+  )
+
+  expect_identical(
+    group_by_if(tbl, is.integer),
```
Comment (krlmlr) [inline tests/testthat/test-colwise-group-by.R]: Perhaps change `gr2` to a `numeric` here?

File: tests/testthat/test-colwise-mutate.R [hunk 8]
```diff
@@ -113,6 +113,54 @@ test_that("can use a purrr-style lambda", {
...
+  )
+})
+
+test_that("summarise variants does not summarise grouping variable (#3351)", {
+  tbl <- data_frame(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
+    group_by(gr1)
+  res <- summarise( tbl, gr2 = mean(gr2), x = mean(x))
+
+  expect_identical( summarise_all(tbl, mean), res)
+  expect_identical( summarise_if(tbl, is.integer, mean), res)
```
Comment (krlmlr) [inline tests/testthat/test-colwise-mutate.R]: Do we have a test for `summarise_at()` trying to access a group variable?

File: tests/testthat/test-colwise-select.R [hunk 9]
```diff
@@ -56,6 +56,24 @@ test_that("can select/rename with vars()", {
...
+
+  expect_identical(
+    select(tbl, gr1),
+    select_at(tbl, vars(gr1))
+  )
+  expect_identical(
+    select_all(tbl),
+    tbl
+  )
+  expect_identical(
```
Comment (krlmlr) [inline tests/testthat/test-colwise-select.R]: This should give a message if `gr1` is not part of the selection. Can you please adapt the test?

File: tests/testthat/test-colwise-select.R [hunk 10]
```diff
@@ -92,3 +110,35 @@ test_that("scoping (#3426)", {
...
+    res
+  )
+
+  expect_identical(
+    rename_if(tbl, is.integer, toupper),
+    res
+  )
+})
+
+test_that("select_all does not change the order of columns (#3351)", {
```
Comment (krlmlr) [inline tests/testthat/test-colwise-select.R]: I like that test. Does the same hold for `mutate_all()` and `transmute_all()`?

File: R/manip.r (hunk 6 above)
Comment (romainfrancois) [reply R/manip.r]: > To avoid the irritating message from transmute_all(), can we just forward transmute_all() to mutate_all(), which is currently silent?

Then what about this ?: 

```
> transmute_all(data_frame(x = 1:3, y = 1:3), funs(mean, sd))
# A tibble: 3 x 4
  x_mean y_mean  x_sd  y_sd
   <dbl>  <dbl> <dbl> <dbl>
1     2.     2.    1.    1.
2     2.     2.    1.    1.
3     2.     2.    1.    1.
> mutate_all(data_frame(x = 1:3, y = 1:3), funs(mean, sd))
# A tibble: 3 x 6
      x     y x_mean y_mean  x_sd  y_sd
  <int> <int>  <dbl>  <dbl> <dbl> <dbl>
1     1     1     2.     2.    1.    1.
2     2     2     2.     2.    1.    1.
3     3     3     2.     2.    1.    1.
```

File: tests/testthat/test-colwise-group-by.R (hunk 7 above)
Comment (romainfrancois) [reply tests/testthat/test-colwise-group-by.R]: done

File: tests/testthat/test-colwise-mutate.R (hunk 8 above)
Comment (romainfrancois) [reply tests/testthat/test-colwise-mutate.R]: yes, a few lines above : 

```r
test_that("summarise_at refuses to treat grouping variables (#3351)", {
  tbl <- data_frame(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
    group_by(gr1)

  expect_error(
    summarise_at(tbl, vars(gr1), mean),
    "Column `gr1` can't be modified because it's a grouping variable",
    fixed = TRUE
  )
})

```

File: tests/testthat/test-colwise-select.R (hunk 9 above)
Comment (romainfrancois) [reply tests/testthat/test-colwise-select.R]: So you're saying this should give a message ?

```
> tbl <- data_frame(gr1 = rep(c(1,2), 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
+     group_by(gr1)
> 
> select_if(tbl, is.integer)
# A tibble: 8 x 3
# Groups:   gr1 [2]
    gr1   gr2     x
  <dbl> <int> <int>
1    1.     1     1
2    2.     1     2
3    1.     1     3
4    2.     1     4
5    1.     2     5
6    2.     2     6
7    1.     2     7
8    2.     2     8
```

File: tests/testthat/test-colwise-select.R (hunk 10 above)
Comment (romainfrancois) [reply tests/testthat/test-colwise-select.R]: I added the test for `mutate_all` but `transmute_all` does not pass. It puts the grouping variables first. 

```r
> tbl <- group_by( tibble( x = 1:4, y = 1:4), y )
> transmute_all(tbl, identity)
# A tibble: 4 x 2
# Groups:   y [4]
      y     x
  <int> <int>
1     1     1
2     2     2
3     3     3
4     4     4
> tbl <- group_by( tibble( x = 1:4, y = 1:4), x )
> transmute_all(tbl, identity)
# A tibble: 4 x 2
# Groups:   x [4]
      x     y
  <int> <int>
1     1     1
2     2     2
3     3     3
4     4     4
> tbl <- group_by( tibble( x = 1:4, y = 1:4, z = 1:4), y )
> transmute_all(tbl, identity)
# A tibble: 4 x 3
# Groups:   y [4]
      y     x     z
  <int> <int> <int>
1     1     1     1
2     2     2     2
3     3     3     3
4     4     4     4
```

File: R/manip.r (hunk 6 above)
Comment (krlmlr) [reply R/manip.r]: I thought they're the same. Bummer.

Let's postpone this for now.

File: tests/testthat/test-colwise-select.R (hunk 9 above)
Comment (krlmlr) [reply tests/testthat/test-colwise-select.R]: I think so, but I'd like to postpone this too.

File: tests/testthat/test-colwise-select.R (hunk 10 above)
Comment (krlmlr) [reply tests/testthat/test-colwise-select.R]: This is consistent with the behavior in dplyr 0.7.4. We can postpone thinking about if we want to change it.

**Comment by krlmlr** [comment]
@romainfrancois: Can you please merge with a descriptive NEWS entry?

**Comment by romainfrancois** [comment]
This is a `fledge` thing right ?

**Comment by romainfrancois** [comment]
I'm getting this:

```
> library(fledge)
> update_news()
Error in commit$sha : $ operator not defined for this S4 class
```

**Comment by krlmlr** [comment]
I haven't tested `update_news()` in isolation yet, I should.

Anyway, you don't need to update the `NEWS.md` as part of this pull request, just supply a commit message with NEWS entries as bullet points. I'll run `bump_version()` later.

**Comment by krlmlr** [comment]
*fledge* seems to require *git2r* from GitHub. Updated `DESCRIPTION` there.

File: NEWS.md [hunk 11]
```diff
@@ -88,13 +88,17 @@
...
 
-* `arrange()` fails gracefully on `data.frame` columns (#3153)
+* `arrange()` fails gracefully on `data.frame` columns (#3153).
 
 * `slice()` no longer enforce tibble classes when input is a simple `data.frame`, and ignores 0 (#3297, #3313).
 
 * Support for raw vector columns in `mutate`, `summarise`, `arrange`, `group_by`
   and joins (minimal `raw` x `raw` support initially) (#1803). 
 
+* `group_by_at` can group by an existing grouping variable (#3351).
```
[the remark this answers is not in the document]
Comment (romainfrancois) [reply NEWS.md]: ✅
