### PR TITLE
across() and c_across() when used out of dplyr context

### LINKED ISSUE #5180: More informative error message when across() is used in wrong context
```r
iris %>% pivot_longer(across(is.numeric))
#> Error: peek_mask() must only be used inside dplyr verbs
```

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5180

``` r
library(dplyr, warn.conflicts = FALSE)
across()
#> Error: across() must only be used inside dplyr verbs
c_across()
#> Error: c_across() must only be used inside dplyr verbs
```

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by romainfrancois** [comment]
@lionel- did you envision more information in the message, perhaps about `across()` arguments ?

File: R/context.R [hunk 1]
```diff
@@ -112,7 +112,10 @@ context_peek_bare <- function(name) {
 }
 context_peek <- function(name, fun, location = "dplyr verbs") {
   context_peek_bare(name) %||%
-    abort(glue("{fun} must only be used inside {location}"))
+    abort(glue("{fun} must only be used inside {location}"),
+      class = "dplyr:::context_peek_error",
```
Comment (romainfrancois) [inline R/context.R:116]: This might not be necessary, this is from a first idea, I can remove `class=` and additional information from here.

Comment (hadley) [reply R/context.R:116]: Yeah I wouldn't worry about class unless we throw the same error in multiple places.
