### PR TITLE
if_any() effectively reducing.

### LINKED ISSUE #5709: On the dev feature if_any/if_all (this is not a bug)
Hi!
I just installed the dev version of `dplyr` to test the new feature produced after #5660.

I run the examples using the next data:
```r
library(dplyr)
library(tibble)
df <- data.frame(
    "ID" = c("asdf","vfdkun", "seifu", "seijd", "qweri"),
    "elephant_zoo" = c(1,1,1,2,0), #Should not be useful there
    "rhino_zoo" = c(1,2,3,1,0), #Should not be useful there
    "hippo_zoo" = c(1,1,0,0,0),
    "elephant_wild_A" = c(0,0,1,1,3),
    "rhino_wild_A" = c(0,0,4,3,1),
    "elephant_wild_B" = c(0,0,0,0,0),
    "rhino_wild_C" = c(0,0,1,5,7),
    "hippo_wild_B" = c(0,0,0,0,0)) %>% 
  column_to_rownames(var = "ID")
df
       elephant_zoo rhino_zoo hippo_zoo elephant_wild_A rhino_wild_A elephant_wild_B rhino_wild_C
asdf              1         1         1               0            0               0            0
vfdkun            1         2         1               0            0               0            0
seifu             1         3         0               1            4               0            1
seijd             2         1         0               1            3               0            5
qweri             0         0         0               3            1               0            7
       hippo_wild_B
asdf              0
vfdkun            0
seifu             0
seijd             0
qweri             0
```
It works as expected, since it works inside `filter`:
```r
df %>% filter(if_any(contains("zoo"), ~`>`(.,0)))
       elephant_zoo rhino_zoo hippo_zoo elephant_wild_A rhino_wild_A elephant_wild_B rhino_wild_C
asdf              1         1         1               0            0               0            0
vfdkun            1         2         1               0            0               0            0
seifu             1         3         0               1            4               0            1
seijd             2         1         0               1            3               0            5
       hippo_wild_B
asdf              0
vfdkun            0
seifu             0
seijd             0
```
But I hoped that it worked beyond that, which is not the case:
```r
df %>%
    mutate(ZOO = 
               case_when(if_any(contains("zoo"), ~`>`(.,0)) ~ "zoo", 
                         TRUE ~ "F"))
Error: Problem with `mutate()` input `ZOO`.
x LHS of case 1 (`if_any(contains("zoo"), ~. > 0)`) must be a logical vector, not a `tbl_df/tbl/data.frame` object.
ℹ Input `ZOO` is `case_when(if_any(contains("zoo"), ~. > 0) ~ "zoo", TRUE ~ "F")`.
Run `rlang::last_error()` to see where the error occurred.
```
So not a single logical vector outside `filter`... Let's try
```r
df %>%
    mutate(ZOO = 
               case_when(pull(if_any(contains("zoo"), ~`>`(.,0))) ~ "zoo", 
                         TRUE ~ "F"))
       elephant_zoo rhino_zoo hippo_zoo elephant_wild_A rhino_wild_A elephant_wild_B rhino_wild_C hippo_wild_B ZOO
asdf              1         1         1               0            0               0            0            0 zoo
vfdkun            1         2         1               0            0               0            0            0 zoo
seifu             1         3         0               1            4               0            1            0   F
seijd             2         1         0               1            3               0            5            0   F
qweri             0         0         0               3            1               0            7            0   F
```
The result is incorrect. Indeed:
```r
df %>%
    mutate(ZOO = pull(if_any(contains("zoo"), ~`>`(.,0))))
       elephant_zoo rhino_zoo hippo_zoo elephant_wild_A rhino_wild_A elephant_wild_B rhino_wild_C hippo_wild_B   ZOO
asdf              1         1         1               0            0               0            0            0  TRUE
vfdkun            1         2         1               0            0               0            0            0  TRUE
seifu             1         3         0               1            4               0            1            0 FALSE
seijd             2         1         0               1            3               0            5            0 FALSE
qweri             0         0         0               3            1               0            7            0 FALSE
```
Let's see:
```r
df %>%
    mutate(ZOO = if_any(contains("zoo"), ~`>`(.,0)))
       elephant_zoo rhino_zoo hippo_zoo elephant_wild_A rhino_wild_A elephant_wild_B rhino_wild_C hippo_wild_B
asdf              1         1         1               0            0               0            0            0
vfdkun            1         2         1               0            0               0            0            0
seifu             1         3         0               1            4               0            1            0
seijd             2         1         0               1            3               0            5            0
qweri             0         0         0               3            1               0            7            0
                                                                                                                                                                           ZOO
asdf                                                                                                                                   \033[38;5;246m# A tibble: 5 x 3\033[39m
vfdkun                                                                                                                                        elephant_zoo rhino_zoo hippo_zoo
seifu  \033[38;5;250m*\033[39m \033[3m\033[38;5;246m<lgl>\033[39m\033[23m        \033[3m\033[38;5;246m<lgl>\033[39m\033[23m     \033[3m\033[38;5;246m<lgl>\033[39m\033[23m    
seijd                                                                                                                 \033[38;5;250m1\033[39m TRUE         TRUE      TRUE     
qweri                                                                                                                 \033[38;5;250m2\033[39m TRUE         TRUE      TRUE     
Warning message:
In format.data.frame(if (omit) x[seq_len(n0), , drop = FALSE] else x,  :
  corrupt data frame: columns will be truncated or padded with NAs
```
Ough!!!

It would be nice to have these functions beyond `filter`. Meanwhile, we wil go on using `any_cols` as in #4770.

Thank you!

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5709

simplified version of @iago-pssjd example: 

``` r
library(dplyr, warn.conflicts = FALSE)
d <- data.frame(x = c(0, 0, 10), y = c(0, 0, 10), z = c(10, 0, 10))
d %>% mutate(
  test = case_when(
    if_all(x:z, ~ . > 8) ~ "all big",
    if_any(x:z, ~ . > 8) ~ "some big",
    TRUE                 ~ "small"
  ))
#>    x  y  z     test
#> 1  0  0 10 some big
#> 2  0  0  0    small
#> 3 10 10 10  all big
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

File: R/across.R [hunk 1]
```diff
@@ -148,19 +148,15 @@ across <- function(.cols = everything(), .fns = NULL, ..., .names = NULL) {
 #' @rdname across
 #' @export
 if_any <- function(.cols, .fns = NULL, ..., .names = NULL) {
-  structure(
-    across({{.cols}}, .fns = .fns, ..., .names = .names),
-    filter_combine = "or"
-  )
+  df <- across({{.cols}}, .fns = .fns, ..., .names = .names)
```
Comment (lionel-) [inline R/across.R:151]: Can you use the recommended style for `{{` please?

```suggestion
  df <- across({{ .cols }}, .fns = .fns, ..., .names = .names)
```

File: R/across.R [hunk 2]
```diff
@@ -148,19 +148,15 @@ across <- function(.cols = everything(), .fns = NULL, ..., .names = NULL) {
...
+  .Call(dplyr_reduce_lgl_or, df)
```
Comment (lionel-) [inline R/across.R:152]: IIUC there is no type checking until the `LOGICAL()` calls. We probably need to coerce (and some unit tests):

```r
df <- vctrs::vec_cast_common(!!!df, .to = logical())
```

File: R/across.R [hunk 3]
```diff
@@ -148,19 +148,15 @@ across <- function(.cols = everything(), .fns = NULL, ..., .names = NULL) {
...
 }
 
 #' @rdname across
 #' @export
 if_all <- function(.cols, .fns = NULL, ..., .names = NULL) {
-  structure(
-    across({{.cols}}, .fns = .fns, ..., .names = .names),
-    filter_combine = "and"
-  )
+  df <- across({{.cols}}, .fns = .fns, ..., .names = .names)
```
Comment (lionel-) [inline R/across.R:158]:
```suggestion
  df <- across({{ .cols }}, .fns = .fns, ..., .names = .names)
```

**Review by lionel- — COMMENTED** [review]
Nice use of `if_any()`!

File: R/across.R (hunk 2 above)
Comment (romainfrancois) [reply R/across.R:152]: oh yes, I'll do this now.

File: R/across.R [hunk 4]
```diff
@@ -148,19 +148,19 @@ across <- function(.cols = everything(), .fns = NULL, ..., .names = NULL) {
 #' @rdname across
 #' @export
 if_any <- function(.cols, .fns = NULL, ..., .names = NULL) {
-  structure(
-    across({{.cols}}, .fns = .fns, ..., .names = .names),
-    filter_combine = "or"
-  )
+  df <- across({{ .cols }}, .fns = .fns, ..., .names = .names)
+  n <- nrow(df)
+  df <- vec_cast_common(!!!df, .to = logical())
```
Comment (hadley) [inline R/across.R:153]: Does this change mean that `if_all()` and `if_any()` won't benefit from the performance in #5697?

File: src/filter.cpp [hunk 5]
```diff
@@ -226,3 +226,26 @@ SEXP dplyr_mask_eval_all_filter(SEXP quos, SEXP env_private, SEXP s_n, SEXP env_
 
   return keep;
 }
+
+SEXP dplyr_reduce_lgl_or(SEXP df, SEXP n_) {
+  int n = INTEGER(n_)[0];
+  return reduce_lgl_or(df, n);
+}
+
+SEXP dplyr_reduce_lgl_and(SEXP df, SEXP n_) {
```
Comment (hadley) [inline src/filter.cpp:235]: Why are these two functions so different?

File: tests/testthat/test-across.R [hunk 6]
```diff
@@ -255,6 +255,15 @@ test_that("across() works with empty data frames (#5523)", {
    )
 })
 
+test_that("if_any() and if_all() enforce logical", {
+  d <- data.frame(x = 10, y = 10)
+  expect_error(filter(d, if_all(x:y, identity)))
```
Comment (hadley) [inline tests/testthat/test-across.R:260]: Add a TODO to use snapshot tests?

File: tests/testthat/test-mutate.r [hunk 7]
```diff
@@ -467,6 +467,21 @@ test_that("can suppress or catch warnings from the outside (#5675)", {
   }
 })
 
+test_that("if_any() and if_all() can be used in mutate() (#5709", {
+  d <- data.frame(x = c(1, 5, 10, 10), y = c(0, 0, 0, 10), z = c(10, 5, 1, 10))
+  res <- d %>% mutate(
+    test = case_when(
```
Comment (hadley) [inline tests/testthat/test-mutate.r:473]: Maybe drop the `case_when()` in order to keep it simple?

File: tests/testthat/test-mutate.r [hunk 8]
```diff
@@ -467,6 +467,21 @@ test_that("can suppress or catch warnings from the outside (#5675)", {
...
+      if_any(x:z, ~ . > 8) ~ "big",
+      TRUE                 ~ "small"
+    ))
+  expect_equal(res$test, c("big", "small", "big", "big"))
+
+  res <- d %>% mutate(
+    test = case_when(
+      if_all(x:z, ~ . > 8) ~ "big",
+      TRUE                 ~ "small"
+    ))
```
Comment (hadley) [inline tests/testthat/test-mutate.r:483]: Missing `expect_equal()`

File: tests/testthat/test-mutate.r [hunk 9]
```diff
@@ -467,6 +467,21 @@ test_that("can suppress or catch warnings from the outside (#5675)", {
   }
 })
 
+test_that("if_any() and if_all() can be used in mutate() (#5709", {
```
Comment (hadley) [inline tests/testthat/test-mutate.r:470]: Should this test live in `test-across.R`?

File: R/across.R (hunk 4 above)
Comment (romainfrancois) [reply R/across.R:153]: The way `filter()` works currently makes it difficult to benefit from the changes of #5697, this can be done but I think it's a follow up pull request.

File: src/filter.cpp (hunk 5 above)
Comment (romainfrancois) [reply src/filter.cpp:209]: Thanks. That was artificial and a memory from when `if_any()` and `if_all()` were implemented by adding an attribute to the result of `across()`. This is no longer relevant now.

File: R/across.R (hunk 4 above)
Comment (romainfrancois) [reply R/across.R:153]: opened https://github.com/tidyverse/dplyr/issues/5715 for follow up

File: src/filter.cpp [hunk 10]
```diff
@@ -226,3 +171,63 @@ SEXP dplyr_mask_eval_all_filter(SEXP quos, SEXP env_private, SEXP s_n, SEXP env_
...
+  }
+
+  SEXP reduced = PROTECT(new_logical(n, FALSE));
+  int* p_reduced = LOGICAL(reduced);
+  if (ncols > 0) {
+    const SEXP* p_df = VECTOR_PTR_RO(df);
+    for (R_xlen_t j = 0; j < ncols; j++) {
+      int* p_df_j = LOGICAL(p_df[j]);
+      for (int i = 0; i < n; i++) {
+        p_reduced[i] = p_reduced[i] == TRUE || p_df_j[i] == TRUE;
```
Comment (DavisVaughan) [inline src/filter.cpp:200]:
```suggestion
        p_reduced[i] = p_reduced[i] || p_df_j[i];
```

Can the comparison be removed?

File: src/filter.cpp [hunk 11]
```diff
@@ -226,3 +171,63 @@ SEXP dplyr_mask_eval_all_filter(SEXP quos, SEXP env_private, SEXP s_n, SEXP env_
...
+  SEXP reduced = PROTECT(new_logical(n, TRUE));
+  int* p_reduced = LOGICAL(reduced);
+
+  if (ncols > 0) {
+    const SEXP* p_df = VECTOR_PTR_RO(df);
+    R_xlen_t ncol = XLENGTH(df);
+    for (R_xlen_t j = 0; j < ncol; j++) {
+      int* p_df_j = LOGICAL(p_df[j]);
+      for (R_xlen_t i = 0; i < n ; i++) {
+        p_reduced[i] = p_reduced[i] == TRUE && p_df_j[i] == TRUE;
```
Comment (DavisVaughan) [inline src/filter.cpp:226]:
```suggestion
        p_reduced[i] = p_reduced[i] && p_df_j[i];
```

File: src/filter.cpp (hunk 10 above)
Comment (romainfrancois) [reply src/filter.cpp:200]: I think not because of NA_LOGICAL but I have to check

Comment (romainfrancois) [reply src/filter.cpp:200]: if I make these two changes, I get: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- expand.grid(
  x = c(TRUE, FALSE, NA), y = c(TRUE, FALSE, NA)
)
filter(df, x, y)
#>      x    y
#> 1 TRUE TRUE
filter(df, x & y)
#>      x    y
#> 1 TRUE TRUE
filter(df, if_all(c(x,y), identity))
#>      x    y
#> 1 TRUE TRUE
#> 2   NA TRUE
#> 3 TRUE   NA
#> 4   NA   NA

filter(df, x | y)
#>       x     y
#> 1  TRUE  TRUE
#> 2 FALSE  TRUE
#> 3    NA  TRUE
#> 4  TRUE FALSE
#> 5  TRUE    NA
filter(df, if_any(c(x,y), identity))
#>       x     y
#> 1  TRUE  TRUE
#> 2 FALSE  TRUE
#> 3    NA  TRUE
#> 4  TRUE FALSE
#> 5    NA FALSE
#> 6  TRUE    NA
#> 7 FALSE    NA
#> 8    NA    NA
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

otherwise, I get: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- expand.grid(
  x = c(TRUE, FALSE, NA), y = c(TRUE, FALSE, NA)
)
filter(df, x, y)
#>      x    y
#> 1 TRUE TRUE
filter(df, x & y)
#>      x    y
#> 1 TRUE TRUE
filter(df, if_all(c(x,y), identity))
#>      x    y
#> 1 TRUE TRUE

filter(df, x | y)
#>       x     y
#> 1  TRUE  TRUE
#> 2 FALSE  TRUE
#> 3    NA  TRUE
#> 4  TRUE FALSE
#> 5  TRUE    NA
filter(df, if_any(c(x,y), identity))
#>       x     y
#> 1  TRUE  TRUE
#> 2 FALSE  TRUE
#> 3    NA  TRUE
#> 4  TRUE FALSE
#> 5  TRUE    NA
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
