### PR TITLE
DataMask<> does nothing when .rm() a name it does not know.

### LINKED ISSUE #4035: Setting a non-existing column to NULL crashes R and RStudio Desktop on Windows
This is not related to the old issue #2196, because it is reproducible in vanilla R on Windows.  Not on RStudio Server Ubuntu

```
library(dplyr)

mtcars %>% 
  mutate(
    mpg = NULL, # no problem
    dummy = NULL # crashes R
  )
```
 ```

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1   
> 
```

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #4035

### CODE REVIEW

File: inst/include/dplyr/data/DataMask.h [hunk 1]
```diff
@@ -373,14 +373,15 @@ class DataMask {
   // remove this variable from the environments
   void rm(const SymbolString& symbol) {
     int idx = symbol_map.find(symbol);
+    if (idx >= 0) {
```
Comment (hadley) [inline inst/include/dplyr/data/DataMask.h]: FWIW I think an early return is clear here:

```R
if (idx < 0)
  return;
```
