### PR TITLE
Fix ownership of errors thrown by internal dplyr steps

### LINKED ISSUE #6139: Take ownership of the `mutate()` step in `group_by()`
To simplify the error message:

```r
mtcars %>%
  group_by(cyl = 1 + "") %>%
  mutate(new = 1 + "")
#> Error in `group_by()` at dplyr/R/mutate.R:156:2:
#> ! Problem adding computed columns.
#> Caused by error in `mutate()`:
#> ! Problem while computing `cyl = 1 + ""`.
#> Caused by error in `1 + ""`:
#> ! non-numeric argument to binary operator
```

### PR DESCRIPTION
**Pull request by lionel-**
Closes #6139.

Also makes `dplyr_error_call()` recursive so that, for example, `mutate()` errors transferred to `add_tally()` can be transferred to `add_count()`.

### CODE REVIEW

File: R/group-by.r [hunk 1]
```diff
@@ -243,14 +250,11 @@ add_computed_columns <- function(.data,
   if (any(needs_mutate)) {
     # TODO: use less of a hack
```
Comment (hadley) [inline R/group-by.r:251]: Can remove this comment now?

File: tests/testthat/_snaps/distinct.md [hunk 2]
```diff
@@ -26,10 +26,8 @@
     Code
       (expect_error(df %>% distinct(y = a + 1)))
     Output
-      <error/rlang_error>
+      <error/dplyr:::mutate_error>
       Error in `distinct()`:
-      ! Problem adding computed columns.
```
Comment (hadley) [inline tests/testthat/_snaps/distinct.md:31]: Nice!

**Review by hadley — APPROVED** [review]

File: R/group-by.r (hunk 1 above)
Comment (lionel-) [reply R/group-by.r:251]: I think the comment refers to `if (inherits(.data, "data.frame"))`, cf https://github.com/tidyverse/dplyr/commit/10b1cf11d3919259523d5c36a5b3262abc235e93.
