### PR TITLE
when a column has not classes but has the object bit set, pretend it …

### LINKED ISSUE #3349: bind_rows: Expecting a string vector: [type=NULL; required=STRSXP].
I am being stuck with dplyr 0.7.4 trying to use `bind_rows()` (initially: unnest()) on a list of data-frames obtained with `broom::augment()`, I get error message: 
*Error in bind_rows_(x, .id) : 
  Expecting a string vector: [type=NULL; required=STRSXP].* 

I don't see what is not working, it seems that this is due to a few offending columns... Am I doing something wrong or is there an issue down there?

```r
library(tidyverse)
library(broom)

reg1 <- lm(y~ ., data=freeny)
reg2 <- lm(y~ . -price.index, data=freeny)
regs_df <- data_frame(name=c("reg1", "reg2"),
                      data=list(reg1, reg2)) %>%
  mutate(aug=map(data, augment))

## doesn't work?
regs_df$aug %>%
  bind_rows()

# seem to be linked to specific variables?
vars_issue <- c(2, 9, 12, 13)

regs_df$aug %>%
  map(~select(., -1*vars_issue)) %>%
  bind_rows()

## what is specific about these variables?
regs_df[1,]$aug[[1]] %>%
  select(vars_issue)
```

Thanks!!

### PR DESCRIPTION
**Pull request by romainfrancois**
…has not. closes #3349

This is pretty straightforward. `stats::model.frame` does weird stuff, and broom was an innocent bystander. Just added some defensive code.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Perhaps can be deprecated once dependency on R passes if/when the underlying R bug is fixed?

Certainly in that case the test here will fail; given that, according to the `is.object` documentation, this situation should _never_ arise, it seems it'll be difficult to create a test.

**Comment by romainfrancois** [comment]
Yeah. We can leave the defensive code just in case, but disable the test once the issue is fixed upstream in R.

**Comment by MichaelChirico** [comment]
sounds good. maybe add a comment to tag for later readers? not sure the best pipeline for dealing with something minor like this that will (hopefully) be hardly visible.

File: tests/testthat/test-binds.R [hunk 1]
```diff
@@ -571,6 +571,13 @@ test_that("bind_rows() accepts lists of dataframe-like lists as first argument",
   expect_identical(bind_rows(list(list(a = 1, b = 2))), tibble(a = 1, b = 2))
 })
 
+test_that("columns that are OBJECT but have NULL class are handled gracefully (#3349)", {
+  mod <- lm(y~ ., data=freeny)
```
Comment (krlmlr) [inline tests/testthat/test-binds.R]: We're trying to follow http://style.tidyverse.org/, the *styler* package gets most of it right with `style_pkg(strict = FALSE)` .

File: inst/include/dplyr/Collecter.h [hunk 2]
```diff
@@ -43,8 +43,8 @@ static bool is_class_known(SEXP x) {
 
 static inline void warn_loss_attr(SEXP x) {
   /* Attributes are lost with unknown classes */
-  if (!is_class_known(x)) {
-    SEXP classes = Rf_getAttrib(x, R_ClassSymbol);
+  SEXP classes = Rf_getAttrib(x, R_ClassSymbol);
+  if (!Rf_isNull(classes) && !is_class_known(x)) {
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Is there a reason to not implement this change in `is_class_known()` ?

Comment (romainfrancois) [reply inst/include/dplyr/Collecter.h]: avoiding to do `Rf_getAttrib(x, R_ClassSymbol)` twice.

while we are here, I don't see the point of 

```
if (!OBJECT(x)) {
    return false;
  }
```

in `inherits_from` which is only called when `OBJECT(x)` is set. 

And the `std::set_intersection` looks a bit overkill, this could exit earlier, as soon as there is at least one class.

Comment (krlmlr) [reply inst/include/dplyr/Collecter.h]: How does this avoid querying the class attribute twice? I'm fine with removing the `classes` variable in this function, fix `is_class_known()`, and only query the classes when constructing the warning (we don't need to optimize for the failure case).

Happy to look at the other problems you mentioned in a separate PR/issue.

File: inst/include/dplyr/Collecter.h [hunk 3]
```diff
@@ -34,7 +34,7 @@ static bool is_class_known(SEXP x) {
     known_classes.insert("integer64");
     known_classes.insert("table");
   }
-  if (OBJECT(x)) {
+  if (OBJECT(x) && !Rf_isNull(Rf_getAttrib(x, R_ClassSymbol))) {
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: I'm starting to understand the problem here. If you want to avoid querying the class symbol and the `OBJECT()` bit twice (and also clean up the code a bit), maybe this check could be added to line 17 in this file? I suspect `inherits_from()` will fail if the class attribute is `NULL`.

Comment (romainfrancois) [reply inst/include/dplyr/Collecter.h]: The `inherits_from` and `is_class_known ` are only used once each anyway. it all looks kind of confusing. But I feel that this patch is good enough for fixing the problem, and we can revisit the code later. 

> I suspect inherits_from() will fail if the class attribute is NULL.

yes that was part of the initial problem.

**Comment by krlmlr** [comment]
Thanks! Could you please resolve conflicts and merge?
