### PR TITLE
Fix arrange(desc(<expression>)). closes #4099

### LINKED ISSUE #4099: Regression? Sorting on descending absolute values
I noticed that with a recent version of dplyr I can't sort on `desc(abs(...))` anymore. This worked fine in the past.

``` r
library(dplyr)

df <- data.frame(x = rep(1, 5), y = c(0, 3, 1.5, -5, 4)) %>%
  mutate(diff = x - y, absdiff = abs(x - y))

# this creates the wrong sort order (ascending instead of descending)
arrange(df, desc(abs(diff)))
#>   x    y diff absdiff
#> 1 1  1.5 -0.5     0.5
#> 2 1  0.0  1.0     1.0
#> 3 1  3.0 -2.0     2.0
#> 4 1  4.0 -3.0     3.0
#> 5 1 -5.0  6.0     6.0

# this works as expected
arrange(df, desc(absdiff))
#>   x    y diff absdiff
#> 1 1 -5.0  6.0     6.0
#> 2 1  4.0 -3.0     3.0
#> 3 1  3.0 -2.0     2.0
#> 4 1  0.0  1.0     1.0
#> 5 1  1.5 -0.5     0.5
```

<sup>Created on 2019-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

File: src/arrange.cpp [hunk 1]
```diff
@@ -64,7 +64,7 @@ SEXP arrange_template(const SlicedTibble& gdf, const QuosureList& quosures, SEXP
         // we need a new quosure that peels off `desc` from the original
         // quosure, and uses the same environment
         Quosure quo(PROTECT(rlang::quo_set_expr(named_quosure.get(), expr)));
-        v = mask.eval(named_quosure.get(), indices_all);
+        v = mask.eval(quo, indices_all);
```
Comment (romainfrancois) [inline src/arrange.cpp]: 🤕
