### PR TITLE
Remove `vars` attribute when empty

### LINKED ISSUE #2772: Dev Version of Filter adds a vars attribute
The new version of `filter` in dplyr (0.5.0.9004) adds a `vars` attribute that is new (does not show in dplyr 0.5.0).  This is causing some tests to fail when using `expect_identical()` because attributes have changed.

Expected behavior is to not have the `vars` attribute

In my tests, the attribute seems always to be `character(0)`, which suggests to me that it is unintentional.  I have struck out finding where it is coming from, though.

```r
## Using CRAN Version - expected and desired behavior
suppressMessages(library(dplyr))                          
packageVersion('dplyr')                                   
#> [1] '0.5.0'
data_frame(id=c(1,2,3)) %>% filter(id==1) %>% attributes()
#> $class
#> [1] "tbl_df"     "tbl"        "data.frame"
#> 
#> $row.names
#> [1] 1
#> 
#> $names
#> [1] "id"

## Using devtools::install_github('tidyverse/dplyr')
suppressMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.5.0.9004'
data_frame(id = c(1, 2, 3)) %>% filter(id == 1) %>% attributes()
#> $class
#> [1] "tbl_df"     "tbl"        "data.frame"
#> 
#> $row.names
#> [1] 1
#> 
#> $names
#> [1] "id"
#> 
#> $vars
#> character(0)
```

### PR DESCRIPTION
**Pull request by lionel-**
Fixes #2772

### CODE REVIEW

File: src/utils.cpp [hunk 1]
```diff
@@ -147,7 +147,12 @@ SymbolVector get_vars(SEXP x) {
 
 void set_vars(SEXP x, const SymbolVector& vars) {
   static SEXP vars_symbol = Rf_install("vars");
-  Rf_setAttrib(x, vars_symbol, vars.get_vector());
+
+  SEXP vars_sexp = vars.get_vector();
```
Comment (krlmlr) [inline src/utils.cpp]: I'd prefer a new method `get_vector_or_nil()`, this pattern might occur for other verbs, too.

Comment (lionel-) [inline src/utils.cpp]: A free function `nil_if_empty()` defined on SEXPs would probably be better then.

Comment (krlmlr) [inline src/utils.cpp]: Yes, a free function could be used elsewhere, too.
