### PR TITLE
Check possible values of keep

### LINKED ISSUE #6375: Dev dplyr error when `keep` is not logical
Currently the error isn't informative

``` r
df <- data.frame(a = 1)
dplyr::inner_join(df, df, by = 'a', keep = 1)
#> Error in `x_key[merge]`:
#> ! Must subset columns with a valid subscript vector.
#> ✖ Subscript `merge` has the wrong type `function`.
#> ℹ It must be logical, numeric, or character.
```

<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by hadley**
Fixes #6375

### CODE REVIEW

File: R/join.r [hunk 1]
```diff
@@ -536,6 +536,9 @@ join_mutate <- function(x,
   check_dots_empty0(...)
 
   na_matches <- check_na_matches(na_matches, error_call = error_call)
+  if (!identical(keep, TRUE) && !identical(keep, FALSE) && !identical(keep, NULL)) {
```
Comment (eutwt) [inline R/join.r:539]: Slightly shorter with rlang functions: `!is_true(keep) && !is_false(keep) && !is_null(keep)`

Comment (hadley) [reply R/join.r]: Good catch, thanks!

File: R/join.r [hunk 2]
```diff
@@ -536,6 +536,9 @@ join_mutate <- function(x,
   check_dots_empty0(...)
 
   na_matches <- check_na_matches(na_matches, error_call = error_call)
+  if (!is_true(keep) && !is_false(keep) && !is.null(keep)) {
+    abort("`keep` must be `TRUE`, `FALSE`, or `NULL`", call = error_call)
+  }
```
Comment (DavisVaughan) [inline R/join.r:541]: A few notes:

- `nest_join()` also uses `keep` but doesn't go through `join_mutate()`, so this check needs to be there too
- You can use `is_bool()` from rlang as another shortcut here
- Added the full stop `.` to the end of the sentence
- It probably makes sense to extract out a helper like `check_unmatched()` and `check_na_matches()`, since you have to use this check in 2 places now.

So maybe:

```r
check_keep <- function(keep, ..., error_call = caller_env()) {
  check_dots_empty0(...)
  
  if (!is_bool(keep) && !is.null(keep)) {
    abort("`keep` must be `TRUE`, `FALSE`, or `NULL`.", call = error_call)
  }
}
```

Plus maybe a `nest_join()` test

**Review by DavisVaughan — CHANGES_REQUESTED** [review]

File: R/join.r (hunk 2 above)
Comment (hadley) [reply R/join.r]: I'm not a fan of the `...` pattern for internal functions like this, so I didn't implement it. But I went with the other suggestions and generally improved the error reporting across the join family.
