### PR TITLE
Fix hybrid evaluation with quosured symbols

### LINKED ISSUE #2822: top_n performance problems in v0.6
`top_n` (and possibly other ranking functions) within `group_by` chains got _really_ slow in the latest master branch version (c7ca3743).
Performance is fine when the number of groups is small, but it appears (in my light testing) that the slowdown is a (rapidly-growing) function of the number of groups.
Observe:
```R
library(tidyverse); library(magrittr)

n_groups <- 10e3
n_obs <- 100e3

x <- sample(n_groups, n_obs, TRUE)
y <- runif(n_obs)
df <- tibble(x, y)

system.time(foo1 <- df %>% group_by(x) %>% top_n(1, y))
#    user  system elapsed
#  4.868   8.328  13.195

system.time(foo2 <- df %>% group_by(x) %>% arrange(desc(y)) %>% mutate(ix = row_number()) %>% filter(ix == 1) %>% select(-ix))
#    user  system elapsed
#   0.440   0.008   0.448

system.time(foo3 <- df %>% group_by(x) %>% arrange(desc(y)) %>% slice(1))
#    user  system elapsed
#  0.112   0.000   0.113

identical(sort(foo1$y), sort(foo2$y)) ## TRUE
identical(sort(foo2$y), sort(foo3$y)) ## TRUE
```
`top_n` performance previously appeared to be similar to the 'naive' foo2 and foo3 variants above.

---

Here's a performance analysis for `n_groups` varying between 1,000 and 10,000:
```R
n_groups <- seq(1e3, 10e3, by = 1e3)
n_obs <- 100e3
results <- lapply(n_groups, function(n) {
    print(n)
    df <- tibble(x = sample(n, n_obs, TRUE), y = runif(n_obs))
    t1 <- system.time(df %>% group_by(x) %>% top_n(1, y))
    t2 <- system.time(df %>% group_by(x) %>% arrange(desc(y)) %>% mutate(ix = row_number()) %>% filter(ix == 1) %>% select(-ix))
    t3 <- system.time(df %>% group_by(x) %>% arrange(desc(y)) %>% slice(1))
    lst(t1, t2, t3)
}) %>% setNames(n_groups)

map_df(results, function(x) map_df(x, "elapsed"), .id = "n_groups")
```
```
 # A tibble: 10 x 4
    n_groups     t1    t2    t3
       <chr>  <dbl> <dbl> <dbl>
  1     1000  1.663 0.201 0.122
  2     2000  3.192 0.268 0.129
  3     3000  4.038 0.226 0.099
  4     4000  5.128 0.269 0.100
  5     5000  6.328 0.297 0.104
  6     6000  7.413 0.323 0.103
  7     7000  8.737 0.358 0.107
  8     8000 10.009 0.399 0.107
  9     9000 11.118 0.418 0.111
 10    10000 12.487 0.453 0.112
```

### PR DESCRIPTION
**Pull request by lionel-**
Closes #2822

### CODE REVIEW

File: tests/testthat/test-hybrid.R [hunk 1]
```diff
@@ -769,3 +769,45 @@ test_that("constant folding and argument matching in hybrid evaluator (#2299)",
     mutate(y = 1) %>%
     summarise(z = first(x, order_by = y))
 })
+
+test_that("simple handlers work with quosured symbols", {
+  mean <- sum <- var <- sd <- bad_hybrid_handler
```
Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: Couldn't we just use `expect_hybrid_result()` here?

Comment (lionel-) [inline tests/testthat/test-hybrid.R]: I think the testing approach in this PR is simpler and immediately grokkable by newcomers.

Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: The hybrid tests in `test-hybrid.R` have the purpose to test if hybrid evaluation is active or not, and all follow the same pattern. I'd rather not introduce a second pattern or scatter these tests over different files.

Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: We could add a comment that describes what the `expect_hybrid..._()` functions are doing.

Comment (lionel-) [inline tests/testthat/test-hybrid.R]: do you mean `check_hybrid..`? These functions would need a `summary = TRUE` argument for non summary handlers. The implementation of the check_hybrid function is already rather complicated and I still don't understand it fully. I think it's much simpler and flexible to check for hybrid handling with locally bound functions.

Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: There's a lot of boilerplate if you do it manually. We can work on simplifying/extending the interface, implementation, and/or documentation, but I'd rather:

1. have all tests that test if hybrid handling is invoked or not in a single file `test-hybrid.R`
2. use a consistent testing pattern/DSL in all these tests

Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: You're right about `summary = TRUE`, we could also use `verb = summarise` or e.g. provide `check_hybrid_summarise()` and `check_hybrid_mutate()` entry points.

Comment (lionel-) [inline tests/testthat/test-hybrid.R]: `check_hyrid_result()` is not much less verbose than using the standard testthat tools.

I'll gather the hybrid tests in the test-hybrid file, though it's already quite big.

Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: Thanks.

`check_hybrid_result()` does avoid repeating the same pattern of `expect_identical(pull(mutate()))` over and over again, it's like a mini-DSL to test a particular detail of the implementation. But I agree that it could use some documentation.

Comment (hadley) [inline tests/testthat/test-hybrid.R]: I really don't like the existing way of testing hybrid code because it's not obvious how it works and I get confused when I try and read through the code.

File: tests/testthat/test-top-n.R [hunk 2]
```diff
@@ -16,3 +16,8 @@ test_that("top_n() handles missing `wt`", {
 test_that("top_n() handles calls", {
   expect_identical(top_n(mtcars, 2, -disp), top_n(mtcars, -2, disp))
 })
+
+test_that("top_n() is hybrided (#2822)", {
```
Comment (hadley) [inline tests/testthat/test-top-n.R]: Hybridised

File: tests/testthat/test-hybrid.R (hunk 1 above)
Comment (krlmlr) [inline tests/testthat/test-hybrid.R]: Sure, we can work on it after release.

Comment (lionel-) [inline tests/testthat/test-hybrid.R]: FWIW I think this is a case where a DSL is distracting.
