### PR TITLE
More improvements to count()

### LINKED ISSUE #5265: count() has had major breaking changes
Count used to work twice in a row to find out how many count values you had, eg:

Counting a combination of vars, and then counting the n would produce a result that told you how many times you had a count of, say, 1 or 2, etc.

Ie, you'd get this:

image

However, now you get an error:

``` r
require(tidyverse)
#> Loading required package: tidyverse

mtcars %>% 
  count(cyl, gear) %>% 
  count(n)
#> Using `n` as weighting variable
#> Error: Column `n` is already present in output.
#> ℹ Use `name = "new_name"` to pick a new name.
```

And if you give the second count a name so as to avoid the conflict, it auto-weights, so the result still is not what was produced originally.

``` r
require(tidyverse)
#> Loading required package: tidyverse

mtcars %>% 
  count(cyl, gear) %>% 
  count(n, name = "nn")
#> Using `n` as weighting variable
#>    n nn
#> 1  1  2
#> 2  2  6
#> 3  4  4
#> 4  8  8
#> 5 12 12
```

While I get that there are ways around this, it seems like an unexpected assumption that a weight should be applied, and it also requires a lot of recoding old things.

### PR DESCRIPTION
**Pull request by hadley**
Fixes #5265. Closes #5109.

### CODE REVIEW

File: R/count-tally.R [hunk 1]
```diff
@@ -15,13 +15,13 @@
 #' @param x A data frame, data frame extension (e.g. a tibble), or a
 #'   lazy data frame (e.g. from dbplyr or dtplyr).
 #' @param ... <[`data-masking`][dplyr_data_masking]> Variables to group by.
-#' @param wt <[`data-masking`][dplyr_data_masking]> If omitted, will count the
-#'   number of rows. If specified, will perform a "weighted" count by summing
-#'   the (non-missing) values of variable `wt`.
+#' @param wt <[`data-masking`][dplyr_data_masking]> Either a expression
+#'   or a numeric constant. If an expression, will perform a "weighted"
+#'   count by summing the (non-missing) values of variable `wt`; if a
+#'   numeric constant will
```
Comment (romainfrancois) [inline R/count-tally.R:21]: Looks like this sentence is unfinished

File: R/count-tally.R [hunk 2]
```diff
@@ -134,31 +136,44 @@ add_tally <- function(x, wt = NULL, sort = FALSE, name = NULL) {
...
+      "Using `n` as weighting variable",
+      i = "Quiet this message with `wt = n` or count rows with `wt = 1`"
+    ))
     wt <- quo(n)
   }
 
   if (quo_is_null(wt)) {
-    quo(n())
+    expr(n())
+  } else if (is.numeric(quo_get_expr(wt))) {
```
Comment (lionel-) [inline R/count-tally.R:149]: This means that `wt = !!x` will now have different semantics based on the size of `x`. This seems a bit unpredictable?

File: R/count-tally.R [hunk 3]
```diff
@@ -134,31 +136,44 @@ add_tally <- function(x, wt = NULL, sort = FALSE, name = NULL) {
...
+    expr(!!quo_get_expr(wt) * n())
```
Comment (lionel-) [inline R/count-tally.R:150]: Why is the quosure unwrapped?
