### PR TITLE
avoid INTEGER(x) when x is size 0.

### LINKED ISSUE #5541: dplyr_group_indices crashes R with malformed arguments
I'm sure there is a smaller reprex possible, but this is a problem reduced from tidyverts/tsibble#194 

The code below will crash R

```r
gr <- structure(list(1:14566, 14567:30980, 30981:48498, 48499:66037),
                ptype = integer(0), 
                class = c("vctrs_list_of","vctrs_vctr", "list"))
nr <- 0L
.Call(dplyr:::dplyr_group_indices, gr, nr)
```

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5541

### CODE REVIEW

File: src/group_data.cpp [hunk 1]
```diff
@@ -1,11 +1,13 @@
 #include "dplyr.h"
 
-SEXP dplyr_group_indices(SEXP rows, SEXP s_nr) {
-  R_xlen_t nr = INTEGER(s_nr)[0];
-  R_xlen_t ng = XLENGTH(rows);
+SEXP dplyr_group_indices(SEXP data, SEXP rows) {
+  R_xlen_t nr = vctrs::short_vec_size(data);
+  if (nr == 0) return dplyr::vectors::empty_int_vector;
```
Comment (lionel-) [inline src/group_data.cpp:5]: Control flow on own line so it's visible:

```suggestion
  if (nr == 0) {
    return dplyr::vectors::empty_int_vector;
  }
```

**Review by lionel- — APPROVED** [review]
Also add unit test, perhaps from Earo's comment?
