### PR TITLE
Use a double loop to apply functions in `across()`

### LINKED ISSUE #4967: wrong column names when using `across` with multiple functions
Hello,

I noticed that `across` mixed up the column names in the output when I used multiple functions all at once. Please see the reprex blow

Thanks!

``` r

library(dplyr, warn.conflicts = FALSE)
options(tibble.width = Inf)

### ok
iris %>%
  group_by(Species) %>%
  summarise_if(is.numeric, ~ mean(.x, na.rm = TRUE))
#> # A tibble: 3 x 5
#>   Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
#> * <fct>             <dbl>       <dbl>        <dbl>       <dbl>
#> 1 setosa             5.01        3.43         1.46       0.246
#> 2 versicolor         5.94        2.77         4.26       1.33 
#> 3 virginica          6.59        2.97         5.55       2.03

iris %>%
  group_by(Species) %>%
  summarise_if(is.numeric, ~ max(.x, na.rm = TRUE))
#> # A tibble: 3 x 5
#>   Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
#> * <fct>             <dbl>       <dbl>        <dbl>       <dbl>
#> 1 setosa              5.8         4.4          1.9         0.6
#> 2 versicolor          7           3.4          5.1         1.8
#> 3 virginica           7.9         3.8          6.9         2.5

### also ok
iris %>%
  group_by(Species) %>%
  summarise(
    across(c(Sepal.Length:Petal.Width), ~ mean(.x, na.rm = TRUE), names = "mean_{col}"),
    across(c(Sepal.Length:Petal.Width), ~ max(.x, na.rm = TRUE), names = "max_{col}")
  ) 
#> # A tibble: 3 x 9
#>   Species    mean_Sepal.Length mean_Sepal.Width mean_Petal.Length
#> * <fct>                  <dbl>            <dbl>             <dbl>
#> 1 setosa                  5.01             3.43              1.46
#> 2 versicolor              5.94             2.77              4.26
#> 3 virginica               6.59             2.97              5.55
#>   mean_Petal.Width max_Sepal.Length max_Sepal.Width max_Petal.Length
#> *            <dbl>            <dbl>           <dbl>            <dbl>
#> 1            0.246              5.8             4.4              1.9
#> 2            1.33               7               3.4              5.1
#> 3            2.03               7.9             3.8              6.9
#>   max_Petal.Width
#> *           <dbl>
#> 1             0.6
#> 2             1.8
#> 3             2.5
```

Output has wrong column names  with multiple functions

```
my_func <- list(
  mean = ~ mean(., na.rm = TRUE),
  max  = ~ max(., na.rm = TRUE)
)

iris %>%
  group_by(Species) %>%
  summarise(across(is.numeric, my_func, names = "{fn}.{col}")) 
#> # A tibble: 3 x 9
#>   Species    mean.Sepal.Length max.Sepal.Length mean.Sepal.Width max.Sepal.Width
#> * <fct>                  <dbl>            <dbl>            <dbl>           <dbl>
#> 1 setosa                  5.01             3.43             1.46           0.246
#> 2 versicolor              5.94             2.77             4.26           1.33 
#> 3 virginica               6.59             2.97             5.55           2.03 
#>   mean.Petal.Length max.Petal.Length mean.Petal.Width max.Petal.Width
#> *             <dbl>            <dbl>            <dbl>           <dbl>
#> 1               5.8              4.4              1.9             0.6
#> 2               7                3.4              5.1             1.8
#> 3               7.9              3.8              6.9             2.5
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #4967 
Part of #4953 

A chunk of the time in `across()` comes from compat-`pmap()` applying checks that we don't need here (like arg recycling).

Also, using `expand.grid()` is probably more work than we need to do vs using a double loop. I think that the use of `expand.grid()` was also the cause of #4967, because it varies the first input fastest (the columns).

```r
library(dplyr, warn.conflicts = FALSE)

n_cols <- 5
n_rows <- 400
split <- 4

df <- tibble(
  g1 = rep(seq_len(n_rows / split), each = split),
  g2 = rep(seq_len(split), times = n_rows / split),
  x1 = rnorm(n_rows),
  x2 = rnorm(n_rows),
  x3 = rnorm(n_rows),
  x4 = rnorm(n_rows),
  x5 = rnorm(n_rows)
)

gdf <- group_by(df, g1, g2)

bench::mark(
  summarize(gdf, across(is.numeric, diff)),
  summarize_if(gdf, is.numeric, diff),
  iterations = 50
)

# master
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 x 6
#>   expression                                   min  median `itr/sec` mem_alloc
#>   <bch:expr>                               <bch:t> <bch:t>     <dbl> <bch:byt>
#> 1 summarize(gdf, across(is.numeric, diff)) 205.8ms 245.1ms      4.07    8.04MB
#> 2 summarize_if(gdf, is.numeric, diff)       10.2ms  11.3ms     84.5   659.23KB
#> # … with 1 more variable: `gc/sec` <dbl>

# This PR
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 x 6
#>   expression                                   min  median `itr/sec` mem_alloc
#>   <bch:expr>                               <bch:t> <bch:t>     <dbl> <bch:byt>
#> 1 summarize(gdf, across(is.numeric, diff)) 156.3ms 185.7ms      5.38    7.61MB
#> 2 summarize_if(gdf, is.numeric, diff)       10.9ms  12.9ms     72.5   659.23KB
#> # … with 1 more variable: `gc/sec` <dbl>
```

Column names and `across()` results now line up:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1:2, y = c("a", "b"))

df %>% 
  summarise(
    across(
      everything(), 
      list(cls = class, type = is.numeric), 
      names = "{col}_{fn}"
    )
  )
#> # A tibble: 1 x 4
#>   x_cls   x_type y_cls     y_type
#>   <chr>   <lgl>  <chr>     <lgl> 
#> 1 integer TRUE   character FALSE
```

This is not a fix for #4953, as there is still a lot of work going on in `across()`. Much of the rest of the time is split between `as_tibble()` and `glue()`. I'm fairly certain the `glue()` calls are repeated between each call to `across()`, and are part of the "up front" work that could be done.

Screen Shot 2020-03-11 at 2 10 42 PM

### CODE REVIEW

File: tests/testthat/test-across.R [hunk 1]
```diff
@@ -55,6 +55,26 @@ test_that("across() correctly names output columns", {
...
+  x <- df %>%
+    summarise(
+      across(
+        everything(),
+        list(cls = class, type = is.numeric),
+        names = "{col}_{fn}"
+      )
+    )
+
+  expect_named(x, c("x_cls", "x_type", "y_cls", "y_type"))
```
Comment (hadley) [inline tests/testthat/test-across.R]: I think it would be a bit more rigorous to use `expect_equal(x, tibble(...))` here

File: tests/testthat/test-across.R [hunk 2]
```diff
@@ -55,6 +55,26 @@ test_that("across() correctly names output columns", {
...
 
+test_that("across() result locations are aligned with column names (#4967)", {
+  df <- tibble(x = 1:2, y = c("a", "b"))
+
+  x <- df %>%
+    summarise(
+      across(
+        everything(),
+        list(cls = class, type = is.numeric),
+        names = "{col}_{fn}"
```
Comment (hadley) [inline tests/testthat/test-across.R]: I think you can omit this argument — ideally the `across()` call would fit on one line
