### PR TITLE
Force `pick()` empty selections to result in 1 row tibbles

### LINKED ISSUE #6685: Let `pick()` support `NULL`
In the documentation:
> `pick()` is useful as a bridge between data-masking functions (like `mutate()` or `group_by()`) and functions with tidy-select behavior (like `select()`).

Therefore, it will be as expected if they both support `NULL` to fall to no grouping.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df <- data.frame(x = 1)
df |> 
  group_by(across(NULL))
#> # A tibble: 1 × 1
#>       x
#>   <dbl>
#> 1     1
df |> 
  group_by(pick(NULL))
#> Error in `group_by()`:
#> ℹ In argument: `pick(NULL)`.
#> Caused by error:
#> ! `pick(NULL)` must be size 1, not 0.

#> Backtrace:
#>      ▆
#>   1. ├─dplyr::group_by(df, pick(NULL))
#>   2. ├─dplyr:::group_by.data.frame(df, pick(NULL))
#>   3. │ └─dplyr::group_by_prepare(.data, ..., .add = .add, error_call = current_env())
#>   4. │   └─dplyr:::add_computed_columns(.data, new_groups, error_call = error_call)
#>   5. │     └─dplyr:::mutate_cols(...)
#>   6. │       ├─base::withCallingHandlers(...)
#>   7. │       └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
#>   8. │         └─mask$eval_all_mutate(quo)
#>   9. │           └─dplyr (local) eval()
#>  10. ├─dplyr:::dplyr_internal_error(...)
#>  11. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
#>  12. │   └─rlang:::signal_abort(cnd, .file)
#>  13. │     └─base::signalCondition(cnd)
#>  14. └─dplyr (local) `<fn>`(`<dpl:::__>`)
#>  15.   └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
```

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.2 (2022-10-31 ucrt)
#>  os       Windows 10 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  Chinese (Simplified)_China.utf8
#>  ctype    Chinese (Simplified)_China.utf8
#>  tz       Asia/Taipei
#>  date     2023-02-06
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.0   2023-01-09 [1] CRAN (R 4.2.2)
#>  digest        0.6.31  2022-12-11 [1] CRAN (R 4.2.2)
#>  dplyr       * 1.1.0   2023-01-29 [1] CRAN (R 4.2.2)
#>  evaluate      0.20    2023-01-17 [1] CRAN (R 4.2.2)
#>  fansi         1.0.4   2023-01-22 [1] CRAN (R 4.2.2)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.1)
#>  fs            1.6.0   2023-01-23 [1] CRAN (R 4.2.2)
#>  generics      0.1.3   2022-07-05 [1] CRAN (R 4.2.1)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.1)
#>  htmltools     0.5.4   2022-12-07 [1] CRAN (R 4.2.2)
#>  knitr         1.42    2023-01-25 [1] CRAN (R 4.2.2)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
#>  pillar        1.8.1   2022-08-19 [1] CRAN (R 4.2.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.1)
#>  purrr         1.0.1   2023-01-10 [1] CRAN (R 4.2.2)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.1)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [1] CRAN (R 4.2.2)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.1)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.1)
#>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.1)
#>  rmarkdown     2.20    2023-01-19 [1] CRAN (R 4.2.2)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
#>  styler        1.9.0   2023-01-15 [1] CRAN (R 4.2.2)
#>  tibble        3.1.8   2022-07-22 [1] CRAN (R 4.2.1)
#>  tidyselect    1.2.0   2022-10-10 [1] CRAN (R 4.2.1)
#>  utf8          1.2.3   2023-01-31 [1] CRAN (R 4.2.2)
#>  vctrs         0.5.2   2023-01-23 [1] CRAN (R 4.2.2)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.1)
#>  xfun          0.37    2023-01-31 [1] CRAN (R 4.2.2)
#>  yaml          2.3.7   2023-01-23 [1] CRAN (R 4.2.2)
#> 
#>  [1] C:/Users/lenovo/AppData/Local/R/win-library/4.2
#>  [2] C:/Program Files/R/R-4.2.2/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #6685

### CODE REVIEW

**Comment by DavisVaughan** [comment]
These builds are going to fail until we resolve `rlang::flatten/flatten_if/squash_if()` usage in dplyr, but it passed locally so is still good for a review

File: R/pick.R [hunk 1]
```diff
@@ -204,9 +212,10 @@ dplyr_pick_tibble <- function(...) {
 
   # Allow recycling between selected columns, in case it is called from
   # a `reframe()` call that modified columns in an earlier expression like
-  # `reframe(df, x = 1, y = pick(x, z))`. This also exactly mimics expansion
-  # into `y = tibble(x, z)`.
-  size <- vec_size_common(!!!out, .call = error_call)
+  # `reframe(df, x = 1, y = pick(x, z))`. This also closely mimics expansion
+  # into `y = tibble(x, z)`, with an empty selection being an exception that
+  # is like `y = tibble(.rows = 1L)` for recycling purposes (#6685).
+  size <- vec_size_common(!!!out, .absent = 1L, .call = error_call)
```
Comment (DavisVaughan) [inline R/pick.R:218]: Adding `.absent = 1L` is the only actual code change

**Review by hadley — APPROVED** [review]
Makes sense to me.
