### PR TITLE
Prevent collapse of data.frame to vector in across (#4867)

### LINKED ISSUE #4867: across within mutate: Can't select within an unnamed vector
Hello,

I tried the new `across()` funtion within `mutate` but got `Can't select within an unnamed vector` error. Please see the reprex below

``` r
library(dplyr, warn.conflicts = FALSE)

DF <- "value
    -0.0970369274475688
    0.131893549586039
    0.0629266495860389
    0.299559132381831
    -0.0128804337656807
    0.0639743960526874
    0.0271669351886552
    0.322395363972391
    0.179591292893632"

DF <- read.table(text = DF, header = TRUE)
```

This worked with `mutate_if`

``` r
DF %>% 
  mutate_if(is.numeric, ~ round(., digits = 1))
#>   value
#> 1  -0.1
#> 2   0.1
#> 3   0.1
#> 4   0.3
#> 5   0.0
#> 6   0.1
#> 7   0.0
#> 8   0.3
#> 9   0.2
```

This gave me error. 

``` r
DF %>% 
  mutate(across(is.numeric, ~ round(., digits = 1)))
#> Error: Can't select within an unnamed vector.

DF %>%
  mutate(across(is.numeric, as.character))
#> Error: Can't select within an unnamed vector.

rlang::last_error()
#> Error: Error: Internal error: Trace data is not square.

rlang::last_error()
# <error/rlang_error>
# Internal error: Trace data is not square.
# Backtrace:
#   1. (function (x, ...) ...
#   2. rlang:::print.rlang_error(x)
#  10. rlang:::format.rlang_error(x, simplify = simplify, fields = fields)
#  12. rlang:::format.rlang_trace(trace, ..., simplify = simplify)
#  13. rlang:::trace_format_branch(x, max_frames, dir, srcrefs)
#  14. rlang:::branch_uncollapse_pipe(trace)
# Run `rlang::last_trace()` to see the full context.

rlang::last_trace()
# <error/rlang_error>
# Internal error: Trace data is not square.
# Backtrace:
#      x
#   1. +-(function (x, ...) ...
#   2. \-rlang:::print.rlang_error(x)
#   3.   +-rlang:::cat_line(format(x, simplify = simplify, fields = fields))
#   4.   | +-base::cat(paste_line(..., .trailing = .trailing), file = file)
#   5.   | \-rlang:::paste_line(..., .trailing = .trailing)
#   6.   |   +-base::paste(chr(...), collapse = "\n")
#   7.   |   \-rlang::chr(...)
#   8.   |     \-rlang::dots_values(...)
#   9.   +-base::format(x, simplify = simplify, fields = fields)
#  10.   \-rlang:::format.rlang_error(x, simplify = simplify, fields = fields)
#  11.     +-base::format(trace, ..., simplify = simplify)
#  12.     \-rlang:::format.rlang_trace(trace, ..., simplify = simplify)
#  13.       \-rlang:::trace_format_branch(x, max_frames, dir, srcrefs)
#  14.         \-rlang:::branch_uncollapse_pipe(trace)

```

What did I miss? Thanks!

### PR DESCRIPTION
**Pull request by courtiol**
Fixes #4867: across() did not work on one column data.frame because a call to `[` was made without setting `drop = FALSE`.

### CODE REVIEW

File: tests/testthat/test-across.R [hunk 1]
```diff
@@ -1,3 +1,10 @@
+test_that("across() works on one column data.frame", {
+  df <- data.frame(x = 1)
+
+  out <- df %>% mutate(across(x, identity))
```
Comment (hadley) [inline tests/testthat/test-across.R]: I think you could just use `across()` here, and can you please use `expect_equal()` to test that output is the same as the input?

**Comment by hadley** [comment]
For future reference, if you include `Fixes #xyz` in the text of the PR, the corresponding issue will be automatically closed when the PR is merged.

File: tests/testthat/test-across.R (hunk 1 above)
Comment (courtiol) [reply tests/testthat/test-across.R]: Done

**Comment by romainfrancois** [comment]
As a sidenote @courtiol I've squashed the two commits of this PR, which means this master has now diverged from your master branch. 

The easiest thing is to delete your fork and fork again if you want to follow up with other pull requests. For future pull requests, I'd suggest you submit a pull request from a branch other than master.
