### PR TITLE
Handle data pronoun in select_vars()

### LINKED ISSUE #2715: .data pronoun does not work inside select verb
The `.data` pronoun does work inside a `select` "verb", whilst it works inside other verbs such as `mutate` and `filter`. I'm not sure whether this was a deliberate omission but having the `.data` pronoun in the `select` verb would prevent accidently selecting a column by position rather than by name if one of the variables isn’t present in the data frame but is present in the global environment.

``` r
suppressPackageStartupMessages(library(dplyr))

df <- tibble(x = 1:10, y = 5)

select(df, x)
#> # A tibble: 10 × 1
#>        x
#>    <int>
#> 1      1
#> 2      2
#> 3      3
#> 4      4
#> 5      5
#> 6      6
#> 7      7
#> 8      8
#> 9      9
#> 10    10

# .data pronoun does not work in select function.
select(df, .data$x)
#> Error: Object `x` not found in data

# Whoops we accidentally selected a column by position rather than by name.
z <- 1
select(df, z)
#> # A tibble: 10 × 1
#>        x
#>    <int>
#> 1      1
#> 2      2
#> 3      3
#> 4      4
#> 5      5
#> 6      6
#> 7      7
#> 8      8
#> 9      9
#> 10    10

sessionInfo()
#> R version 3.4.0 (2017-04-21)
#> Platform: x86_64-apple-darwin16.5.0 (64-bit)
#> Running under: macOS Sierra 10.12.4
#> 
#> Matrix products: default
#> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#> LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
#> 
#> locale:
#> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dplyr_0.5.0.9004
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.10     digest_0.6.12    rprojroot_1.2    assertthat_0.2.0
#>  [5] R6_2.2.0         backports_1.0.5  magrittr_1.5     evaluate_0.10   
#>  [9] rlang_0.0.0.9018 stringi_1.1.5    lazyeval_0.2.0   rmarkdown_1.5   
#> [13] tools_3.4.0      stringr_1.2.0    glue_1.0.0       yaml_2.1.14     
#> [17] compiler_3.4.0   htmltools_0.3.5  knitr_1.15.1     tibble_1.3.0
```

### PR DESCRIPTION
**Pull request by lionel-**
Closes #2715

Also add advice about passing dots to `select_vars()` (forgot to do it in previous PR).

### CODE REVIEW

File: R/select-vars.R [hunk 1]
```diff
@@ -109,9 +138,26 @@ select_vars <- function(vars, ..., include = character(), exclude = character())
   sel
 }
 
+is_data_pronoun <- function(expr) {
+  identical(node_car(expr), quote(`$`)) &&
```
Comment (hadley) [inline R/select-vars.R]: Actually this also needs support for `[[`
