### PR TITLE
Fix compilation on Windows

### LINKED ISSUE #2638: dplyr not compiling on Windows 10
I'm getting a compile error when installing dplyr from GitHub.  Thanks, Bob

---

```r
Restarting R session...

> library("devtools")
> devtools::install_github("tidyverse/dplyr")
Downloading GitHub repo tidyverse/dplyr@master
from URL https://api.github.com/repos/tidyverse/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/rlang@ac7498c9
from URL https://api.github.com/repos/hadley/rlang/zipball/ac7498c9
Installing rlang
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/muenchen/AppData/Local/Temp/Rtmp0IyXF8/devtoolsdf87d535405/hadley-rlang-ac7498c"  \
  --library="C:/Program Files/R/R-3.3.3/library" --install-tests 

* installing *source* package 'rlang' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c attrs.c -o attrs.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c capture.c -o capture.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c eval.c -o eval.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c export.c -o export.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c internals.c -o internals.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c pairlist.c -o pairlist.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c replace-na.c -o replace-na.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c splice.c -o splice.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c symbol.c -o symbol.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c unquote.c -o unquote.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o rlang.dll tmp.def attrs.o capture.o eval.o export.o init.o internals.o pairlist.o replace-na.o splice.o symbol.o unquote.o utils.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-33~1.3/bin/x64 -lR
installing to C:/Program Files/R/R-3.3.3/library/rlang/libs/x64
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rlang)
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/muenchen/AppData/Local/Temp/Rtmp0IyXF8/devtoolsdf841cd3a04/tidyverse-dplyr-8ba7bc9"  \
  --library="C:/Program Files/R/R-3.3.3/library" --install-tests 

* installing *source* package 'dplyr' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING   -I"C:/Program Files/R/R-3.3.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.3.3/library/BH/include" -I"C:/Program Files/R/R-3.3.3/library/bindrcpp/include" -I"C:/Program Files/R/R-3.3.3/library/plogr/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/r/headers.h:50:0,
                 from C:/Program Files/R/R-3.3.3/library/Rcpp/include/RcppCommon.h:29,
                 from C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp.h:27,
                 from ../inst/include/dplyr/main.h:4,
                 from dplyr_types.h:1,
                 from RcppExports.cpp:4:
RcppExports.cpp: In function 'SEXPREC* dplyr_get_date_classes_try()':
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/macros/macros.h:31:9: warning: unused variable 'rcpp_output_type' [-Wunused-variable]
     int rcpp_output_type = 0 ;                                                                   \
         ^
RcppExports.cpp:256:1: note: in expansion of macro 'BEGIN_RCPP'
 BEGIN_RCPP
 ^
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/macros/macros.h:32:10: warning: unused variable 'rcpp_output_condition' [-Wunused-variable]
     SEXP rcpp_output_condition = R_NilValue ;                                                    \
          ^
RcppExports.cpp:256:1: note: in expansion of macro 'BEGIN_RCPP'
 BEGIN_RCPP
 ^
RcppExports.cpp: In function 'SEXPREC* dplyr_get_time_classes_try()':
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/macros/macros.h:31:9: warning: unused variable 'rcpp_output_type' [-Wunused-variable]
     int rcpp_output_type = 0 ;                                                                   \
         ^
RcppExports.cpp:285:1: note: in expansion of macro 'BEGIN_RCPP'
 BEGIN_RCPP
 ^
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/macros/macros.h:32:10: warning: unused variable 'rcpp_output_condition' [-Wunused-variable]
     SEXP rcpp_output_condition = R_NilValue ;                                                    \
          ^
RcppExports.cpp:285:1: note: in expansion of macro 'BEGIN_RCPP'
 BEGIN_RCPP
 ^
RcppExports.cpp: In function 'SEXPREC* dplyr_build_index_cpp_try(SEXP)':
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/macros/macros.h:31:9: warning: unused variable 'rcpp_output_type' [-Wunused-variable]
     int rcpp_output_type = 0 ;                                                                   \
         ^
RcppExports.cpp:314:1: note: in expansion of macro 'BEGIN_RCPP'
 BEGIN_RCPP
 ^
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/macros/macros.h:32:10: warning: unused variable 'rcpp_output_condition' [-Wunused-variable]
     SEXP rcpp_output_condition = R_NilValue ;                                                    \
          ^
RcppExports.cpp:314:1: note: in expansion of macro 'BEGIN_RCPP'
 BEGIN_RCPP
 ^
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING   -I"C:/Program Files/R/R-3.3.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.3.3/library/BH/include" -I"C:/Program Files/R/R-3.3.3/library/bindrcpp/include" -I"C:/Program Files/R/R-3.3.3/library/plogr/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c address.cpp -o address.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING   -I"C:/Program Files/R/R-3.3.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.3.3/library/BH/include" -I"C:/Program Files/R/R-3.3.3/library/bindrcpp/include" -I"C:/Program Files/R/R-3.3.3/library/plogr/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c api.cpp -o api.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING   -I"C:/Program Files/R/R-3.3.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.3.3/library/BH/include" -I"C:/Program Files/R/R-3.3.3/library/bindrcpp/include" -I"C:/Program Files/R/R-3.3.3/library/plogr/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c arrange.cpp -o arrange.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING   -I"C:/Program Files/R/R-3.3.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.3.3/library/BH/include" -I"C:/Program Files/R/R-3.3.3/library/bindrcpp/include" -I"C:/Program Files/R/R-3.3.3/library/plogr/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c between.cpp -o between.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DRCPP_USING_UTF8_ERROR_STRING   -I"C:/Program Files/R/R-3.3.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.3.3/library/BH/include" -I"C:/Program Files/R/R-3.3.3/library/bindrcpp/include" -I"C:/Program Files/R/R-3.3.3/library/plogr/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c bind.cpp -o bind.o
In file included from C:/Program Files/R/R-3.3.3/library/Rcpp/include/RcppCommon.h:179:0,
                 from C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp.h:27,
                 from pch.h:1,
                 from bind.cpp:1:
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap.h: In instantiation of 'SEXPREC* Rcpp::internal::wrap_dispatch_unknown_iterable(const T&, Rcpp::traits::false_type) [with T = long long unsigned int; SEXP = SEXPREC*; Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]':
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap.h:732:98:   required from 'SEXPREC* Rcpp::internal::wrap_dispatch_unknown(const T&, Rcpp::traits::false_type) [with T = long long unsigned int; SEXP = SEXPREC*; Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap.h:770:96:   required from 'SEXPREC* Rcpp::internal::wrap_dispatch_eigen(const T&, Rcpp::traits::false_type) [with T = long long unsigned int; SEXP = SEXPREC*; Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap.h:787:80:   required from 'SEXPREC* Rcpp::internal::wrap_dispatch_unknown_importable(const T&, Rcpp::traits::false_type) [with T = long long unsigned int; SEXP = SEXPREC*; Rcpp::traits::false_type = Rcpp::traits::integral_constant<bool, false>]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap.h:807:99:   required from 'SEXPREC* Rcpp::internal::wrap_dispatch(const T&, Rcpp::traits::wrap_type_unknown_tag) [with T = long long unsigned int; SEXP = SEXPREC*]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap_end.h:30:110:   required from 'SEXPREC* Rcpp::wrap(const T&) [with T = long long unsigned int; SEXP = SEXPREC*]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/grow.h:49:46:   required from 'SEXPREC* Rcpp::internal::grow__dispatch(Rcpp::traits::true_type, const T&, SEXP) [with T = Rcpp::traits::named_object<long long unsigned int>; SEXP = SEXPREC*; Rcpp::traits::true_type = Rcpp::traits::integral_constant<bool, true>]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/grow.h:65:86:   required from 'SEXPREC* Rcpp::grow(const T&, SEXP) [with T = Rcpp::traits::named_object<long long unsigned int>; SEXP = SEXPREC*]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/generated/grow__pairlist.h:50:60:   required from 'SEXPREC* Rcpp::pairlist(const T1&, const T2&, const T3&, const T4&) [with T1 = SEXPREC*; T2 = SEXPREC*; T3 = Rcpp::traits::named_object<long long unsigned int>; T4 = Rcpp::traits::named_object<long long unsigned int>; SEXP = SEXPREC*]'
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/generated/Function__operator.h:50:74:   required from 'SEXPREC* Rcpp::Function_Impl<StoragePolicy>::operator()(const T1&, const T2&, const T3&, const T4&) const [with T1 = SEXPREC*; T2 = SEXPREC*; T3 = Rcpp::traits::named_object<long long unsigned int>; T4 = Rcpp::traits::named_object<long long unsigned int>; StoragePolicy = Rcpp::PreserveStorage; SEXP = SEXPREC*]'
../inst/include/dplyr/bad.h:44:48:   required from 'void dplyr::bad_pos_arg(int, C1, C2, C3) [with C1 = const char*; C2 = Rcpp::traits::named_object<long long unsigned int>; C3 = Rcpp::traits::named_object<long long unsigned int>]'
bind.cpp:86:84:   required from here
C:/Program Files/R/R-3.3.3/library/Rcpp/include/Rcpp/internal/wrap.h:525:11: error: invalid conversion from 'long long unsigned int' to 'SEXP' [-fpermissive]
  SEXP x = object ;
           ^
make: *** [bind.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="dplyr.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o filter.o group_by.o group_indices.o hybrid.o hybrid_count.o hybrid_debug.o hybrid_in.o hybrid_minmax.o hybrid_nth.o hybrid_offset.o hybrid_simple.o hybrid_window.o init.o init_register.o join.o join_exports.o mutate.o rlang-export.o select.o set.o slice.o summarise.o test.o utils.o window.o"' had status 2
ERROR: compilation failed for package 'dplyr'
* removing 'C:/Program Files/R/R-3.3.3/library/dplyr'
* restoring previous 'C:/Program Files/R/R-3.3.3/library/dplyr'
Error: Command failed (1)
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0

loaded via a namespace (and not attached):
[1] httr_1.2.1    R6_2.2.0      tools_3.3.3   withr_1.0.2   curl_2.3      memoise_1.0.0 knitr_1.15.1 
[8] git2r_0.18.0  digest_0.6.12
```

### PR DESCRIPTION
**Pull request by krlmlr**
- need to wrap `R_xlen_t` for building error messages

@hadley: The code seems to use `int`, `size_t` and `R_xlen_t` pretty much interchangeably, and calls `Rf_length()` instead of `Rf_xlength()`. This will cause trouble for vectors or data frames with > 2G rows. How important is this? (The GCC switch `-Wconversion` detects these mistakes.)

Closes #2638.

### CODE REVIEW

File: inst/include/dplyr/workarounds/xlen.h [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#ifndef DPLYR_WORKAROUND_XLEN_H
+#define DPLYR_WORKAROUND_XLEN__H
+
+namespace Rcpp {
+
+template <>
+inline SEXP wrap(const R_xlen_t& x) {
```
Comment (lionel-) [inline inst/include/dplyr/workarounds/xlen.h]: how come a R_xlen_t gets wrapped? is it from the bind code?

Comment (krlmlr) [inline inst/include/dplyr/workarounds/xlen.h]: Yes, when putting together an error message that mentions the number of rows/columns.

Comment (lionel-) [inline inst/include/dplyr/workarounds/xlen.h]: ah got it. Looks good. Is there any drawback to switching to `R_xlen_t` for size type everywhere? Just read the internals manual and can't see any drawback. The only tricky part it seems is that `base::length()` returns an integer and thus NA if the vector is too long.

Comment (krlmlr) [inline inst/include/dplyr/workarounds/xlen.h]: `Rf_xlength()` returns `R_xlen_t`, and `base::length()` returns a `double` if the result is too large (if `LONG_VECTOR_SUPPORT` is enabled).

`R_xlen_t` is defined as `ptrdiff_t` and (I think) signed, using it everywhere instead of `size_t` will require a fair number of casts. I think we should use both `R_xlen_t` and `size_t` where appropriate.

Comment (lionel-) [inline inst/include/dplyr/workarounds/xlen.h]: > base::length() returns a double

I see in the manual: "At present length returns NA for long vectors, but it may be safer to make that an error."

> using it everywhere instead of size_t will require a fair number of casts

I can see that many casts would be needed during a transition. But if we used it everywhere would that still be the case?

Comment (krlmlr) [inline inst/include/dplyr/workarounds/xlen.h]: In the R-devel sources I see:

```c
SEXP attribute_hidden do_length(SEXP call, SEXP op, SEXP args, SEXP rho)
{
    checkArity(op, args);
    check1arg(args, call, "x");

    SEXP x = CAR(args), ans;

    if (isObject(x) &&
       DispatchOrEval(call, op, "length", args, rho, &ans, 0, 1)) {
	if (length(ans) == 1 && TYPEOF(ans) == REALSXP) {
	    double d = REAL(ans)[0];
	    if (R_FINITE(d) && d >= 0. && d <= INT_MAX && floor(d) == d)
		return coerceVector(ans, INTSXP);
	}
	return(ans);
    }


#ifdef LONG_VECTOR_SUPPORT
    // or use IS_LONG_VEC
    R_xlen_t len = xlength(x);
    if (len > INT_MAX) return ScalarReal((double) len);
#endif
    return ScalarInteger(length(x));
}
```

Maybe the docs need an update, or the behavior is different for R 3.3.3? Haven't checked.

The casts (or perhaps a helper function or a wrapper class) are needed to avoid warnings, because `std::vector<>::size()` returns a `size_t`. (These warnings are only visible with `-Wconversion`.) But standardizing on one type for sizes sounds like a good idea in general.

**Comment by hadley** [comment]
@krlmlr few people have complained about the absence of long-vector support, so it's currently low priority.

**Comment by krlmlr** [comment]
Yeah, we just need to remember to use `-Wconversion` and search for `Rf_length` to find all related problems in the code.
