### PR TITLE
full_join(na_matches = "never")

### LINKED ISSUE #5359: `full_join()` with `na_matches = "never"` breaks depending on order of input
`full_join()` with an `NA` in the joining variable and `na_matches = "never"` only works if the dataframe containing the `NA` value is the first argument (`x`), but not the second (`y`).

Expected output: same results regardless of the order of the input dataframes.

``` r
library(tibble)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dat1 <- tibble(
  name = c("a", "c"),
  var1 = c(1, 2)
)

dat2 <- tibble(
  name = c("a", "c"),
  var2 = c(3, 4)
)

dat3 <- tibble(
  name = c("a", NA_character_),
  var3 = c(5, 6)
)

# works
full_join(dat1, dat2, by = "name", na_matches = "never")
#> # A tibble: 2 x 3
#>   name   var1  var2
#>   <chr> <dbl> <dbl>
#> 1 a         1     3
#> 2 c         2     4

# works
full_join(dat2, dat1, by = "name", na_matches = "never")
#> # A tibble: 2 x 3
#>   name   var2  var1
#>   <chr> <dbl> <dbl>
#> 1 a         3     1
#> 2 c         4     2

# works
full_join(dat3, dat1, by = "name", na_matches = "never")
#> # A tibble: 3 x 3
#>   name   var3  var1
#>   <chr> <dbl> <dbl>
#> 1 a         5     1
#> 2 <NA>      6    NA
#> 3 c        NA     2

# fails
full_join(dat1, dat3, by = "name", na_matches = "never")
#> Error in if (any(miss_x)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       macOS Catalina 10.15.5      
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Asia/Tokyo                  
#>  date     2020-06-26                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.1.8   2020-06-17 [1] CRAN (R 4.0.0)
#>  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
#>  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools      2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
#>  dplyr       * 1.0.0   2020-05-29 [1] CRAN (R 4.0.0)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
#>  fs            1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
#>  generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.0)
#>  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
#>  knitr         1.29    2020-06-23 [1] CRAN (R 4.0.0)
#>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
#>  pillar        1.4.4   2020-05-05 [1] CRAN (R 4.0.0)
#>  pkgbuild      1.0.8   2020-05-07 [1] CRAN (R 4.0.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
#>  processx      3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
#>  ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
#>  remotes       2.1.1   2020-02-15 [1] CRAN (R 4.0.0)
#>  rlang         0.4.6   2020-05-02 [1] CRAN (R 4.0.0)
#>  rmarkdown     2.3     2020-06-18 [1] CRAN (R 4.0.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble      * 3.0.1   2020-04-20 [1] CRAN (R 4.0.0)
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
#>  usethis       1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.0)
#>  vctrs         0.3.1   2020-06-05 [1] CRAN (R 4.0.0)
#>  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
#>  xfun          0.15    2020-06-21 [1] CRAN (R 4.0.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

### PR DESCRIPTION
**Pull request by romainfrancois**
This seems to be fixing #5359 but quite possible I'm missing cases.

### CODE REVIEW

File: R/join-rows.R [hunk 1]
```diff
@@ -36,6 +36,7 @@ join_rows <- function(x_key, y_key, type = c("inner", "left", "right", "full"),
 
   if (type == "right" || type == "full") {
     miss_x <- !vec_in(y_key, x_key, na_equal = na_equal)
+    miss_x[is.na(miss_x)] <- TRUE
```
Comment (hadley) [inline R/join-rows.R:39]: I think this would be slightly clearer if you put it in `if (!na_equal) { }`, since that's the only time `miss_x` should contain missing values.
