### PR TITLE
eval_tidy() the top_across() call with the right mask and caller env

### LINKED ISSUE #5734: Referencing other columns inside mutate/summarise across is broken in 1.0.4
In dplyr 1.0.3 you can reference other columns in the same data-frame/tibble group by name. This functionality is broken in 1.0.4

To reproduce, the following example works in 1.0.3

    storms %>% mutate(across(c('wind', 'pressure'), function(x) {
      return(x/lat)
    }))

In 1.0.4, running the above example results in the following error message

> \>rlang::last_error()
> <error/dplyr:::mutate_error>
> Problem with `mutate()` input `..1`.
> x object 'lat' not found

i.e. we can't reference other columns by name. A possible workaround is to use `cur_data()$name_of_column` but this is slower as the following benchmark demonstrates:

    library(dplyr, warn.conflicts = F)
    
    df <- tibble(cbind.data.frame(
      grp_1 = sort(rep(1:250, 4)),
      grp_2 = rep(1:4, 250), 
      matrix(rnorm(1000 * 100), nrow = 1000)))
    
    bench::mark(iterations = 100,
                filter_gc = FALSE,
                use_cur_data = df %>% summarise(across(is.numeric, function(x) {
                  rows = cur_data()
                  mask = (rows$grp_1 %% 2) == 0
                  return(mean(x[mask] / rows$grp_2[mask]))
                })),
                direct_reference = df %>% summarise(across(is.numeric, function(x) {
                  mask = (grp_1 %% 2) == 0
                  return(mean(x[mask] / grp_2[mask]))
                }))) %>%
      select(expression, min, median, `itr/sec`, `gc/sec`)

which results in the following output

    # A tibble: 2 x 5
      expression            min   median `itr/sec` `gc/sec`
      <bch:expr>       <bch:tm> <bch:tm>     <dbl>    <dbl>
    1 use_cur_data       17.2ms  18.29ms      51.1    10.7 
    2 direct_reference   8.12ms   8.59ms     108.      9.76

TL;DR In dply 1.0.3, using `cur_data()$column_name` to reference columns instead of directly using the column names can be considerably slower. In 1.0.4 referencing columns by name, not using cur_data, is currently broken.

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5734

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(x = 1, y = 2)
df %>% 
  mutate(across('x', function(.x) {
    return(.x/y)
  }))
#>     x y
#> 1 0.5 2
```

OTOH, this does not work: 

```r
f <- function(.x) .x / y
df %>% mutate(across('x', f))
#> Error: Problem with `mutate()` input `..1`.
#> x object 'y' not found
#> ℹ Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
```

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

File: R/across.R [hunk 1]
```diff
@@ -233,11 +233,10 @@ across_setup_impl <- function(cols, fns, names, .caller_env, mask = peek_mask("a
...
     #        but perhaps it is time to review how across_cols() work
     mask$set_current_group(1L)
-  } else {
-    # The real `across()` is evaluated in a data mask so we need to remove the
-    # mask layer from the quosure environment (#5460)
-    cols <- quo_set_env(cols, data_mask_top(quo_get_env(cols), recursive = FALSE, inherit = TRUE))
   }
+  # `across()` is evaluated in a data mask so we need to remove the
+  # mask layer from the quosure environment (#5460)
+  cols <- quo_set_env(cols, data_mask_top(quo_get_env(cols), recursive = FALSE, inherit = TRUE))
```
Comment (romainfrancois) [inline R/across.R:239]: now need to do in both case because the `top_across()` call is also evaluated with a data mask

File: R/across.R [hunk 2]
```diff
@@ -270,17 +269,7 @@ across_setup_impl <- function(cols, fns, names, .caller_env, mask = peek_mask("a
...
-      f_rhs(fn) <- call2(
-        quote(rlang::eval_tidy),
-        expr_protect(f_rhs(fn)),
-        data = mask$get_rlang_mask()
-      )
-    }
-    fn <- as_function(fn)
-    fn
-  })
+  fns <- map(fns, as_function)
```
Comment (romainfrancois) [inline R/across.R:272]: nice bonus is that we don't need this 🏋️ no more, , because in this case the formula is evaluated within the mask, and so this finds `y`: 

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(x = 1, y = 2)
df %>% 
  mutate(across('x', ~ .x / y))
#>     x y
#> 1 0.5 2
```

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Review by lionel- — COMMENTED** [review]
So the cols argument of `across()` is evaluated outside of the mask but the fn argument is evaluated inside? If so it might be useful to mention this in a comment. I don't understand the full picture but locally that seems a better approach.

**Comment by romainfrancois** [comment]
In both cases the expression `across(cols, ...)` or the instrumented `top_across()` is evaluated inside, with an `eval_tidy()` which gives "for free" the feature we're trying to fix here. 

But then `cols` is further delayed with: 

```
  # `across()` is evaluated in a data mask so we need to remove the
  # mask layer from the quosure environment (#5460)
  cols <- quo_set_env(cols, data_mask_top(quo_get_env(cols), recursive = FALSE, inherit = TRUE))
  
  vars <- tidyselect::eval_select(cols, data = mask$across_cols())
```

Which I believe make it evaluate outside ?

**Comment by lionel-** [comment]
That makes sense. It feels like something is out of place here though. Probably the mask-bypassing should be done in tidyselect instead of here.

And looking at the tidyselect issues, it looks like past-me agrees :) https://github.com/r-lib/tidyselect/issues/206

**Comment by romainfrancois** [comment]
yeah, you have this `FIXME` also: 

```r
# FIXME: This pattern should be encapsulated by rlang
data_mask_top <- function(env, recursive = FALSE, inherit = FALSE) {
  while (env_has(env, ".__tidyeval_data_mask__.", inherit = inherit)) {
    env <- env_parent(env_get(env, ".top_env", inherit = inherit))
    if (!recursive) {
      return(env)
    }
  }

  env
}
```
