### PR TITLE
Fix tidyeval infloop

### LINKED ISSUE #4049: filter() with two conditions freezes R
This

    iris %>% filter(Sepal.Length > 7) %>% filter(Petal.Length < 6)

works fine (gives two rows), but this one:

    iris %>% filter(Sepal.Length > 7, Petal.Length < 6)

freezes R...

I'm using dplyr v0.7.99.9000, installed from github just before test.

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.99.9000

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5   compiler_3.5.1     magrittr_1.5       assertthat_0.2.0   R6_2.3.0           tools_3.5.1       
 [7] pillar_1.3.1.9000  glue_1.3.0         rstudioapi_0.8     tibble_1.4.99.9006 crayon_1.3.4       Rcpp_1.0.0        
[13] packrat_0.5.0      pkgconfig_2.0.2    rlang_0.3.0.9002   purrr_0.2.5.9000  
```

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #4049

### CODE REVIEW

File: inst/include/dplyr/data/DataMask.h [hunk 1]
```diff
@@ -500,23 +504,42 @@ class DataMask {
...
     if (TYPEOF(expr) == LANGSXP && Rf_inherits(CAR(expr), "rlang_lambda_function")) {
+      // FIXME: Mutation
       SET_CLOENV(CAR(expr), mask_resolved) ;
     }
 
-    // evaluate the call in the data mask
-    SEXP res = Rcpp_fast_eval(expr, data_mask);
+#if (R_VERSION < R_Version(3, 5, 0))
+    Rcpp::Environment env_rlang = Rcpp::Environment::namespace_env("rlang");
+    SEXP rlang_eval_tidy = env_rlang["eval_tidy"];
```
Comment (lionel-) [inline inst/include/dplyr/data/DataMask.h]: Should this be cached? Should we worry about inlining `eval_tidy()`, causing ugly backtraces (with base R, the function would be abbreviated in rlang backtraces)?

File: src/arrange.cpp [hunk 2]
```diff
@@ -41,13 +41,36 @@ SEXP arrange_template(const SlicedTibble& gdf, const QuosureList& quosures, SEXP
...
+        v = binding->get_data();
+      }
+    }
+
+    // otherwise need to evaluate in the data mask
+    if (v.isNULL()) {
+      if (is_desc) {
+        // we need a new quosure that peels off `desc` from the original
+        // quosure, and uses the same environment
+        Quosure quo(PROTECT(rlang::quo_set_expr(named_quosure.get(), expr)));
```
Comment (lionel-) [inline src/arrange.cpp]: Good catch that `quo_set_expr()` returns a fresh pointer, I think I would have forgotten!

File: vignettes/two-table.Rmd [hunk 3]
```diff
@@ -14,6 +14,19 @@ library(dplyr)
 knit_print.tbl_df <- function(x, options) {
   knitr::knit_print(trunc_mat(x), options)
 }
+
+options(
```
Comment (lionel-) [inline vignettes/two-table.Rmd]: Leftover from debugging.

File: inst/include/dplyr/data/DataMask.h (hunk 1 above)
Comment (romainfrancois) [reply inst/include/dplyr/data/DataMask.h]: I'll replace with not inlined then. I guess I can cache `rlang::eval_tidy`. Perhaps the conditional compiling should all go to the C++ `rlang::eval_tidy` rather than here.

File: src/arrange.cpp (hunk 2 above)
Comment (romainfrancois) [reply src/arrange.cpp]: I checked. I just did not want to have have to protect all the quosures ;-)

File: vignettes/two-table.Rmd (hunk 3 above)
Comment (romainfrancois) [reply vignettes/two-table.Rmd]: Thanks. ✅

File: inst/include/dplyr/data/DataMask.h (hunk 1 above)
Comment (romainfrancois) [reply inst/include/dplyr/data/DataMask.h]: ✅

**Comment by DavisVaughan** [comment]
Just FYI, this seems to also fix the issues I was having regarding `slice()`. Before this PR, with dev dplyr and rlang, this was hanging:

```r
library(dplyr)
slice(iris, 1:3)
```

But with the PR, all good.
