### PR TITLE
hybrid evaluation simplifies dplyr::foo to foo. closes #3309

### LINKED ISSUE #3309: row_number() produces error when calling with namespace (dplyr::) in filter()
I would expect `dplyr::row_number()` to give the same output as I get with `row_number()`. But if I use it within `filter()` I get the expected results if I use the plain version but an error if I use the namespaced version.

```r
# Repex:
# This works fine:
filter(mtcars, row_number() == 6L)

# This gives an error:
filter(mtcars, dplyr::row_number() == 6L)
# Error in filter_impl(.data, quo) : 
#   Evaluation error: argument "x" is missing, with no default.
```

### PR DESCRIPTION
**Pull request by romainfrancois**
- hybrid evaluation simplifies calls prefixed with the dplyr namespace (#3309)

### CODE REVIEW

File: src/hybrid.cpp [hunk 1]
```diff
@@ -141,8 +141,18 @@ Result* get_handler(SEXP call, const ILazySubsets& subsets, const Environment& e
 
   if (TYPEOF(call) == LANGSXP) {
     int depth = Rf_length(call);
+
     HybridHandlerMap& handlers = get_handlers();
+
+    // interpret dplyr::fun() as fun(). #3309
     SEXP fun_symbol = CAR(call);
+    if (TYPEOF(fun_symbol) == LANGSXP &&
+        CAR(fun_symbol) == Rf_install("::") &&
```
Comment (krlmlr) [inline src/hybrid.cpp]: Can we use `R_DoubleColonSymbol` ?
