### PR TITLE
Check type of `desc()`

### LINKED ISSUE #6028: Confusing error when forgetting to pipe input (i.e., first arg isn't a dataframe)
Students often forget pipes. I wonder if we could make clearer errors in that case. The error for `arrange` is particularly inscrutable:

``` r
library(tidyverse)
diamonds %>% 
  group_by(cut) %>% 
  summarize(n = n())
  arrange(desc(n))
#> Warning in is.na(x): is.na() applied to non-(list or vector) of type 'closure'
#> Error in x[!nas]: object of type 'closure' is not subsettable
```

<sup>Created on 2021-09-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The other possible errors in this pipeline are also confusing (`no applicable method for 'group_by' applied to an object of class "function"` and `Error: `n()` must only be used inside dplyr verbs.`)

The errors in this particular pipeline could be improved somewhat by adding an informational `group_by.default`, tweaking the logic around the existing `n()` error, and some additional type-checking in `desc`. `ggplot` has some nice messaging like `"Did you use %>% instead of +?"`.

Vaguely related: #4127

### PR DESCRIPTION
**Pull request by hadley**
Fixes #6028

### CODE REVIEW

File: R/desc.r [hunk 1]
```diff
@@ -13,4 +13,10 @@
 #' desc(first_day)
 #'
 #' starwars %>% arrange(desc(mass))
-desc <- function(x) -xtfrm(x)
+desc <- function(x) {
+  if (!vctrs::vec_is(x)) {
+    abort("`x` must be a vector")
+  }
```
Comment (DavisVaughan) [inline R/desc.r:19]: `vec_assert(x)`? That's basically this but with an even more informative (and classed) error

Comment (DavisVaughan) [reply R/desc.r:19]: Also we import vctrs so no need for `vctrs::`

**Review by DavisVaughan — APPROVED** [review]

File: R/desc.r (hunk 1 above)
Comment (hadley) [reply R/desc.r]: How did I miss that 😆
