### PR TITLE
expand_across() can access lexical scope.

### LINKED ISSUE #5862: across(fns=) evaluation
This is what breaks `skimr::skim_by_type()` on the revdeps: https://github.com/tidyverse/dplyr/issues/5810 

```r
#' @export
skim_by_type.data.frame <- function(mangled_skimmers, variable_names, data) {
  skimmed <- dplyr::summarize(
    data,
    dplyr::across(variable_names, mangled_skimmers$funs)
  )
  build_results(skimmed, variable_names, NULL)
}
```

reprexified: 

``` r
library(dplyr, warn.conflicts = FALSE)

f <- function(data, cols, fn_list) {
  data %>% 
    summarise(
      across({{ cols }}, fn_list$funs)
    )
}

f(mtcars, c(mpg, cyl), list(funs = mean))
#> Error: Problem with `summarise()` input `..1`.
#> ℹ `..1 = across(c(mpg, cyl), fn_list$funs)`.
#> x object 'fn_list' not found
```

however this works when `fn_list$funs` is inlined

``` r
f <- function(data, cols, fn_list) {
  data %>% 
    summarise(
      across({{ cols }}, !!fn_list$funs)
    )
}
f(mtcars, c(mpg, cyl), list(funs = mean))
#>        mpg    cyl
#> 1 20.09062 6.1875
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I believe the problem is here: https://github.com/tidyverse/dplyr/blob/master/R/across.R#L505

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5862

``` r
library(dplyr, warn.conflicts = FALSE)

f <- function(data, cols, fn_list) {
  data %>% 
    summarise(
      across({{ cols }}, fn_list$funs)
    )
}

f(mtcars, c(mpg, cyl), list(funs = mean))
#>        mpg    cyl
#> 1 20.09062 6.1875
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

seems to fix `skimr::skim()` too: 

``` r
skimr::skim(iris)
```

|                                                  |      |
| :----------------------------------------------- | :--- |
| Name                                             | iris |
| Number of rows                                   | 150  |
| Number of columns                                | 5    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |      |
| Column type frequency:                           |      |
| factor                                           | 1    |
| numeric                                          | 4    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |      |
| Group variables                                  | None |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts               |
| :------------- | ---------: | -------------: | :------ | --------: | :------------------------ |
| Species        |          0 |              1 | FALSE   |         3 | set: 50, ver: 50, vir: 50 |

**Variable type: numeric**

| skim\_variable | n\_missing | complete\_rate | mean |   sd |  p0 | p25 |  p50 | p75 | p100 | hist  |
| :------------- | ---------: | -------------: | ---: | ---: | --: | --: | ---: | --: | ---: | :---- |
| Sepal.Length   |          0 |              1 | 5.84 | 0.83 | 4.3 | 5.1 | 5.80 | 6.4 |  7.9 | ▆▇▇▅▂ |
| Sepal.Width    |          0 |              1 | 3.06 | 0.44 | 2.0 | 2.8 | 3.00 | 3.3 |  4.4 | ▁▆▇▂▁ |
| Petal.Length   |          0 |              1 | 3.76 | 1.77 | 1.0 | 1.6 | 4.35 | 5.1 |  6.9 | ▇▁▆▇▂ |
| Petal.Width    |          0 |              1 | 1.20 | 0.76 | 0.1 | 0.3 | 1.30 | 1.8 |  2.5 | ▇▁▇▅▃ |

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

File: R/across.R [hunk 1]
```diff
@@ -502,7 +502,7 @@ expand_across <- function(quo) {
 
   setup <- across_setup(
     !!cols,
-    fns = eval_tidy(expr$.fns, mask),
+    fns = eval_tidy(expr$.fns, mask, env = env),
     names = eval_tidy(expr$.names, mask),
```
Comment (romainfrancois) [inline R/across.R:506]: is it needed for `names` too ?

**Comment by romainfrancois** [comment]
I believe `diseq` has the same problem:

```
> test_check("diseq")
══ Skipped tests ═══════════════════════════════════════════════════════════════
● On CRAN (2)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-basic.R:20:3): Model can be simulated ───────────────────────────
Error: Problem with `mutate()` input `..1`.
ℹ `..1 = dplyr::across(where(is.factor), remove_unused_levels)`.
✖ object 'remove_unused_levels' not found
Backtrace:
     █
  1. ├─diseq:::load_or_simulate_model("diseq_basic", parameters) test-basic.R:20:2
  2. │ └─methods::new(...) helper-common.R:136:4
  3. │   ├─methods::initialize(value, ...)
  4. │   └─diseq:::initialize(value, ...)
  5. │     └─diseq:::.local(.Object, ...)
  6. │       ├─methods::callNextMethod(...)
  7. │       │ └─base::eval(call, callEnv)
  8. │       │   └─base::eval(call, callEnv)
  9. │       └─diseq:::.nextMethod(...)
 10. │         └─diseq:::.local(.Object, ...)
 11. │           ├─methods::callNextMethod(...)
 12. │           │ └─base::eval(call, callEnv)
 13. │           │   └─base::eval(call, callEnv)
 14. │           └─diseq:::.nextMethod(...)
 15. │             └─diseq:::.local(.Object, ...)
 16. │               └─`%>%`(...)
 17. ├─dplyr::mutate(., dplyr::across(where(is.factor), remove_unused_levels))
 18. ├─dplyr:::mutate.data.frame(...)
 19. │ └─dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
 20. │   ├─base::withCallingHandlers(...)
 21. │   └─dplyr:::expand_across(dots[[i]])
 22. │     ├─dplyr:::across_setup(...)
 23. │     └─rlang::eval_tidy(expr$.fns, mask)
 24. └─base::.handleSimpleError(...)
 25.   └─dplyr:::h(simpleError(msg, call))
 ```

File: R/across.R (hunk 1 above)
Comment (lionel-) [reply R/across.R:506]: Yes I think so.

**Review by lionel- — APPROVED** [review]
